/** @type {HTMLCanvasElement} */



let gameStarted = false;
let keysPressed = {};             //Object that will store the events generated bye the keydown
let lastKeyPressed = '';



//Event Listener used to detect the keys pressed
//Used with conditional and objects to detect to keys pressed at the same time
//Enabling the player to move on a diagonal



document.addEventListener('keydown', (e) => {
    if(gameStarted){         
    switch(e.code) {

        case 'ArrowUp':
            player.speedY =- player.speed;
            keysPressed.ArrowUp = true;
            player.lastKeyPressed = 'ArrowUp';
            player.noKeyPressed= 'Pressed'; 
            break;

        case 'ArrowDown':
             player.speedY = player.speed;
             keysPressed.ArrowDown = true;
             player.lastKeyPressed = 'ArrowDown';
             player.noKeyPressed= 'Pressed'; 
             break;   
             
        case 'ArrowLeft':
             player.speedX = -player.speed;
             keysPressed.ArrowLeft = true;
             player.lastKeyPressed = 'ArrowLeft';
             player.noKeyPressed= 'Pressed'; 
             break;  
        case 'ArrowRight':
             player.speedX = player.speed;
             keysPressed.ArrowRight = true;
             player.lastKeyPressed = 'ArrowRight';
             player.noKeyPressed= 'Pressed'; 
             break;  
        case 'Space':
             shot.x = player.x;
             shot.y = player.y;
             //shot.stopShot();
             if(!shot.shotFired)shot.lastKey = lastKeyPressed;
             if(!shot2.shotFired)shot2.lastKey = lastKeyPressed;
             if(!shot3.shotFired)shot3.lastKey = lastKeyPressed;
             if(!shot4.shotFired)shot4.lastKey = lastKeyPressed;
             if(!shot5.shotFired)shot5.lastKey = lastKeyPressed;
             if(!shot6.shotFired)shot6.lastKey = lastKeyPressed;
             reload.fireShot();
             break;
        
        }
                
                

    if(keysPressed.ArrowUp  && keysPressed.ArrowLeft ) {
       lastKeyPressed = 'ArrowUpLeft';  
      

    }else if(keysPressed.ArrowUp  && keysPressed.ArrowRight ){
       lastKeyPressed = 'ArrowUpRight'
       

    } else if(keysPressed.ArrowDown  && keysPressed.ArrowLeft ){
        lastKeyPressed = 'ArrowDownLeft';
        

    } else if(keysPressed.ArrowDown && keysPressed.ArrowRight){
        lastKeyPressed = 'ArrowDownRight'; 
        

    } else if(keysPressed.ArrowUp){
        lastKeyPressed = 'ArrowUp'

    } else if(keysPressed.ArrowDown){
        lastKeyPressed = 'ArrowDown'
                    
    } else if(keysPressed.ArrowLeft){
        lastKeyPressed = 'ArrowLeft'

    } else if(keysPressed.ArrowRight){
        lastKeyPressed ='ArrowRight';
 
    } 
                
}        
});
   


document.addEventListener('keyup', (e) => {

    if(gameStarted){
    switch(e.code) {
    case 'ArrowUp':
        player.speedY = 0;
        keysPressed.ArrowUp = false;
        player.noKeyPressed= 'None'; 
        break;

    case 'ArrowDown':
        player.speedY = 0;
        keysPressed.ArrowDown = false;
        player.noKeyPressed = 'None'; 
        break;   
        
    case 'ArrowLeft':
        player.speedX = 0;
        keysPressed.ArrowLeft = false;
        player.noKeyPressed = 'None'; 
        break;  

    case 'ArrowRight':
        player.speedX = 0;
        keysPressed.ArrowRight = false;
        player.noKeyPressed = 'None'; 
        break; 

        
          

    }
    }
}) 

