var P=["#9bbc0f","#8bac0f","#306230","#0f380f"],F=["#FF6633","#FF9933","#FFCC33"],W=["#0099ff","#0033cc","#3366ff"],T=["#6633FF","#0099cc","#ffff33"],B=["#8bac0f","#306230","#8A0808","#B43104","#FE2E2E"];function ArcadeAudio(){this.sounds={}}ArcadeAudio.prototype.add=function(a,b,c){this.sounds[a]=[];c.forEach(function(c,e){this.sounds[a].push({tick:0,count:b,pool:[]});for(var f=0;f<b;f++){var g=new Audio;g.src=jsfxr(c);this.sounds[a][e].pool.push(g)}},this)};
ArcadeAudio.prototype.play=function(a){window.mute||(a=this.sounds[a],a=1<a.length?a[Math.floor(Math.random()*a.length)]:a[0],a.pool[a.tick].play(),a.tick<a.count-1?a.tick++:a.tick=0)};var aa=new ArcadeAudio;aa.add("coin",5,[[0,,.0116,.3061,.432,.4097,,,,,,.5982,.6732,,,,,,1,,,,,.5],[0,,.0375,.5038,.3663,.6874,,,,,,.5943,.5286,,,,,,1,,,,,.5]]);
aa.add("shoot",4,[[3,.4699,.211,.7699,.4133,.1018,,-.18,,,,,,,,,,,1,,,,,.5],[3,.4285,.171,.7738,.4352,.1018,,-.1522,-.008,.0491,,,.0013,.0333,-.0433,,-.0242,,1,.0351,.0193,.0468,.0409,.5],[3,.4122,.0712,.864,.5086,.1269,.0632,-.1067,.0362,.0066,.0432,-.0515,.0472,,-.0953,.031,.0369,-.0206,1,.0859,.1004,.0517,.0036,.5]]);
aa.add("hit",5,[[3,,.1302,.5325,.4565,.7702,,-.395,,,,-.608,.8726,,,,,,1,,,,,.5],[3,.0715,.0928,.4473,.4449,.8587,,-.3921,.0103,.0067,.0994,-.6284,.9041,.0273,-.0337,.0569,.09,-.1048,1,.0013,.0967,,.0768,.5],[3,,.2697,.3528,.4129,.1622,,.0306,,,,,,,,,.209,-.2744,1,,,,,.5]]);aa.add("death",5,[[0,.07,.2,.4199,.25,.4158,,-.4261,,.25,.0599,-.34,.6899,.28,-.1,,-.0199,-.0199,1,-.0277,,.05,-.0199,.5]]);
aa.add("slowmo",5,[[0,.1489,.0657,.0741,.8508,.6885,,,-.171,,.079,-.6692,.8491,.0362,-.0111,,.0048,.1977,.6197,.3364,.3787,,-.0113,.5]]);aa.add("start",1,[[0,,.044,.4721,.4696,.7453,,,,,,.3999,.5163,,,,,,1,,,,,.5]]);window.cr="true"==localStorage.getItem("cr");window.mute="true"==localStorage.getItem("mute");crbutton.textContent="Graphics: "+(window.cr?"Low":"High");mutebutton.textContent="Sounds: "+(window.mute?"Off":"On");sanitize=function(a){for(var b=0;b<a.length;b++)a[b]|=0;return a};
CanvasRenderingContext2D.prototype.fr=function(){var a=Array.prototype.slice.apply(arguments);cr&&sanitize(a);this.fillRect.apply(this,a)};CanvasRenderingContext2D.prototype.tr=function(){var a=Array.prototype.slice.apply(arguments);cr&&sanitize(a);this.translate.apply(this,a)};randBetween=function(a,b,c){if(1==arguments.length)if(a instanceof Array)b=a[1],a=a[0];else return a;var d=Math.random()*(b-a)+a;return c?Math.floor(d):d};clamp=function(a,b,c){return Math.min(Math.max(a,b),c)};
Array.prototype.maxInRange=function(a,b){return 0<=a&&b<=this.length&&a<b?Math.max.apply(null,this.slice(a,b)):NaN};Array.prototype.random=function(){return 1>=this.length?this[0]||null:this[randBetween(0,this.length,1)]};Array.prototype.copy=function(){return 2==this.length?new Vector2d(this[0],this[1]):this.slice()};noop=function(a){return a};Object.prototype.mixin=function(a){for(var b in a)a.hasOwnProperty(b)&&!this.hasOwnProperty(b)&&(this[b]=a[b]);return this};
Object.prototype.markForRemoval=function(){this.isAlive=this.isVisible=!1;this.isMarked=!0;if(this.onRemove)this.onRemove();this.resources&&(this.resources.length=0)};var __extends=this.__extends||function(a,b){function c(){this.constructor=a}for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);c.prototype=b.prototype;a.prototype=new c};able=function(a,b){for(var c=0;c<a.length;c++)b?a[c].classList.remove("d"):a[c].classList.add("d")};
var body=document.body,allButtons=Array.prototype.slice.call(document.getElementsByClassName("button")),aspect=228.5/154;
function calculateCanvasDimensions(){var a=wrapper.offsetWidth,b=wrapper.offsetHeight,c=clamp(.95*body.clientWidth,228.5,1E3),d=clamp(.95*body.clientHeight,228.5/aspect,1E3/aspect),b=Math.max(a/c,b/d);wrapper.style.width=a/b+"px";wrapper.style.height=a/aspect/b+"px";veil.style.width=wrapper.style.width;veil.style.height=wrapper.style.height;document.body.style.fontSize=Math.round(16*(wrapper.offsetWidth-228.5)/800+8)+"px";clearTimeout(calculateCanvasDimensions.timeout);calculateCanvasDimensions.timeout=
setTimeout(function(){for(var b=0;b<allButtons.length;b++){var a=allButtons[b],c=a.getContext("2d");c.fillStyle=P[3];c.fillRect(0,0,a.width,a.height);c.imageSmoothingEnabled=!1;c.webkitImageSmoothingEnabled=!1;var d=spritePosCache[a.id];c.drawImage(imglol,d[0],d[1],d[2],d[3],0,0,a.width,a.height)}},200)}var spritePosCache={"72b":[0,12,15,16],"74b":[30,12,15,16],"75b":[60,12,15,16],"76b":[90,12,15,16],"87t":[120,15,10,10],"83b":[130,15,10,10],"32s":[126,1,11,11]};calculateCanvasDimensions();
window.onresize=function(a){calculateCanvasDimensions()};setTimeout(calculateCanvasDimensions,500);document.body.addEventListener("touchmove",function(a){a.preventDefault()});
var Frame=function(){function a(b,a,d,e,f){this.img=b;this.x=a;this.y=d;this.w=e;this.h=f}a.prototype.drawItself=function(b,a,d,e,f){200>Math.abs(a+translation)&&b.drawImage(this.img,this.x,this.y,this.w,this.h,a,d,this.w,this.h)};return a}(),Animation=function(){function a(b,a,d,e){this.img=b;this.width=a;this.height=d;this.frames=[];this.currentFrame=this.length=0;this.isReady=!1;this.frameLength=e;this.remainder=0}a.prototype.init=function(){this.length=this.frames.length;this.isReady=!0};a.prototype.reset=
function(){this.remainder=this.currentFrame=0};a.prototype.pushNewFrame=function(b,a){this.frames.push(new Frame(this.img,b,a,this.width,this.height))};a.prototype.drawFrame=function(b,a,d,e,f,g){this.isReady||this.init();a=this.remainder+a;var h=a/this.frameLength|0;this.remainder=a%this.frameLength;this.skip(h).drawItself(b,d,e,f,g)};a.prototype.skip=function(a){this.currentFrame=(this.currentFrame+a)%this.length;0>this.currentFrame&&(this.currentFrame=this.length+this.currentFrame);return this.frames[this.currentFrame]};
return a}(),SpriteSheet=function(){function a(a,c){this.img=a;this.callback=c;var d=this;this.img.onload=function(){d.width=d.img.width;d.height=d.img.height;d.callback(d)};if(this.img.width)this.img.onload()}a.prototype.getXYFor=function(a,c,d,e){a=a*c+e[0];c=this.width;return[a%c,Math.floor(a/c)*d+e[1]]};a.prototype.loadImage=function(a,c){this.isReady=!0;a.apply(c,[this])};a.prototype.getAnimation=function(a,c,d,e,f,g){e=new Animation(this.img,a,c,e/(d.length||d));f="number"===typeof f?this.getXYFor(f,
a,c,[0,0]):f;if("number"===typeof d){var h=[];for(g=0;g<d;g++)h.push(g);d=h}for(g=0;g<d.length;g++)h=this.getXYFor(d[g],a,c,f),e.pushNewFrame(h[0],h[1]);return e};return a}(),Vector2d=function(){function a(a,c){this[0]=a||0;this[1]=c||0}a.random=function(b){b=b||1;var c=Math.random()*b-b/2;b=Math.random()*b-b/2;return new a(c,b)};a.prototype.set=function(a){this[0]=a[0];this[1]=a[1]};a.prototype.add=function(a){return[this[0]+a[0],this[1]+a[1]]};a.prototype.doAdd=function(a){this[0]+=a[0];this[1]+=
a[1];return this};a.prototype.substract=function(a){return[this[0]-a[0],this[1]-a[1]]};a.prototype.doSubstract=function(a){this[0]-=a[0];this[1]-=a[1];return this};a.prototype.multiply=function(a){return[this[0]*a,this[1]*a]};a.prototype.doMultiply=function(a){this[0]*=a;this[1]*=a;return this};a.prototype.getMagnitude=function(){return Math.sqrt(this[0]*this[0]+this[1]*this[1])};a.prototype.copy=function(){return new a(this[0],this[1])};Array.prototype.mixin(a.prototype);return a}(),PhysicsBody=
function(){function a(a,c,d,e){this.center=a||new Vector2d;this.corner=c||new Vector2d;this.speed=d||new Vector2d;this.acceleration=e||new Vector2d;this.angularSpeed=this.rotation=0;this.friction=.006}a.EPSILON=.005;a.XLIMIT=.5;a.YLIMIT=.5;a.prototype.tick=function(a){this.move(this.speed.multiply(a));this.rotate(this.angularSpeed*a);this.speed.doAdd(this.acceleration.multiply(a));this.speed.doMultiply(1-this.friction*a);this.limitSpeed()};a.prototype.move=function(a){this.center.doAdd(a);return this};
a.prototype.applyAcceleration=function(a,c){this.speed.doAdd(a.multiply(c));this.limitSpeed()};a.prototype.limitSpeed=function(){var b=this.speed.getMagnitude();0!=b&&(b<a.EPSILON?this.speed.doMultiply(0):(Math.abs(this.speed[0])>a.XLIMIT&&(this.speed[0]=clamp(this.speed[0],-a.XLIMIT,a.XLIMIT)),Math.abs(this.speed[1])>a.YLIMIT&&(this.speed[1]=clamp(this.speed[1],-a.YLIMIT,a.YLIMIT))));Math.abs(this.angularSpeed)<a.EPSILON&&(this.angularSpeed=0)};a.prototype.intersects=function(a){return Math.abs(this.center[0]-
a.center[0])>this.corner[0]+a.corner[0]||Math.abs(this.center[1]-a.center[1])>this.corner[1]+a.corner[1]?!1:!0};a.prototype.getLTWH=function(){return[this.center[0]-this.corner[0],this.center[1]-this.corner[1],2*this.corner[0],2*this.corner[1]]};a.prototype.rotate=function(a){this.rotation+=a};a.prototype.gravitateTo=function(a,c){c=Math.max(c,16);this.speed=a.substract(this.center).multiply(c/2E3)};return a}(),Entity=function(){function a(){this.resources=[]}a.prototype.kind=-1;a.prototype.isVisible=
!0;a.prototype.isAlive=!0;a.prototype.isOnGround=!1;a.prototype.isMarked=!1;a.prototype.life=Infinity;a.prototype.draw=noop;a.prototype.collideAction=noop;a.prototype.applyGravity=noop;a.prototype.collideGround=noop;a.prototype.onRemove=noop;a.prototype.animate=function(a,c){if(this.isAlive){this.body.tick(c);if(this.onAnimate)this.onAnimate(a,c);this.resources&&this.resources.forEach(function(d){d.tick(a,c)});this.life-=c;(0>this.life||this.life>this._life)&&this.markForRemoval()}};return a}(),EntityKind=
{FIRETARGET:0,WATERTARGET:1,POISONTARGET:2,LIGHTNINGTARGET:3,PARTICLE:92,BUBBLE:91,COLLECTIBLE:90,FIREBALL:40,WATERBOLT:41,POISONBALL:42,LIGHTNINGBOLT:43,FIREEMITTER:50,WATEREMITTER:51,POISONEMITTER:52,LIGHTNINGEMITTER:53,PLAYER:11,SPRITE:10},SpriteEntity=function(a){function b(b,d,e,f,g){a.call(this);this.kind=EntityKind.SPRITE;this.animations=[];this.currentAnimation=0;this.body=new PhysicsBody(d.copy(),new Vector2d(e/2,f/2));this.spritesheet=b;this.scale=[1,1];this.loadAnimations(g)}__extends(b,
a);b.prototype.loadAnimations=function(a){for(var b=0;b<a.length;b++){var e=this.spritesheet.getAnimation.apply(this.spritesheet,a[b]);this.animations.push(e)}};b.prototype.reset=function(){this.currentAnimation=0};b.prototype.setAnimation=function(a){this.animations[a]&&(this.animations[a].reset(),this.currentAnimation=a)};b.prototype.draw=function(a,b,e){this.animations[this.currentAnimation].drawFrame(a,e,this.body.center[0]-this.body.corner[0],this.body.center[1]-this.body.corner[1],this.scale[0],
this.scale[1])};return b}(Entity),Particle=function(a){function b(a,b,e,f,g){this.fill.apply(this,arguments)}__extends(b,a);b.kind=EntityKind.PARTICLE;b.prototype.fill=function(b,d,e,f,g){a.call(this);this.kind=EntityKind.PARTICLE;this.color=e;this.body=new PhysicsBody(b,new Vector2d(d/2,d/2));this.life=this._life=f||300;this.gravityFactor=1;this.restitution=.3;this.shrinkage=(g?d/2/this.life:0)*g};b.prototype.draw=function(a,b,e){var f=this.body.getLTWH();b=f[0];e=f[1];var g=f[2],f=f[3];a.save();
a.tr(b+g/2,e+f/2);a.rotate(this.body.rotation);a.fillStyle=this.color;a.fr(-g/2,-f/2,g,f);a.restore()};b.prototype.onAnimate=function(a,b){this.body.corner.doSubstract([this.shrinkage*b,this.shrinkage*b])};b.prototype.applyGravity=function(a,b){this.body.applyAcceleration(a.multiply(this.gravityFactor),b)};b.prototype.collideGround=function(a){this.body.speed[1]*=-this.restitution;this.body.speed[0]*=this.restitution;this.body.angularSpeed*=-this.restitution;this.body.limitSpeed();0==this.body.speed.getMagnitude()&&
(this.isOnGround=!0,this.body.angularSpeed=0)};return b}(Entity),Bubble=function(a){function b(a,b,e,f,g,h){this.fill.apply(this,arguments);this.fillIt=h}__extends(b,a);b.kind=EntityKind.BUBBLE;b.prototype.fill=function(a,b,e,f,g){this.kind=EntityKind.BUBBLE;this.color=e;this.body=new PhysicsBody(a,new Vector2d(b/2,b/2));this.life=this._life=f||300;this.gravityFactor=1;this.shrinkage=(g?b/2/this.life:0)*g};b.prototype.draw=function(a,b,e){var f=this.body.getLTWH();b=f[0];e=f[1];var g=f[2],f=f[3];
a.save();a.tr(b+g/2,e+f/2);a.beginPath();a.arc(0,0,this.body.corner.getMagnitude(),0,2*Math.PI,!1);this.fillIt?(a.fillStyle=this.color,a.fill()):(a.strokeStyle=this.color,a.stroke());a.restore()};b.prototype.onAnimate=function(a,b){b<this.life?this.body.corner.doAdd([this.shrinkage*b,this.shrinkage*b]):this.collideGround()};b.prototype.applyGravity=function(a,b){this.body.applyAcceleration(a.multiply(this.gravityFactor),b)};b.prototype.collideGround=function(a){this.markForRemoval();(new Explosion({colors:[this.color],
shrink:1,count:[5,7],strength:.15,offset:new Vector2d(0,-.1),center:this.body.center,gravityFactor:1,life:200})).fire(this.body.center,World.instance)};return b}(Entity),Collectible=function(a){function b(a,b,e,f){this.fill.apply(this,arguments);this.fillIt=!0}__extends(b,a);b.kind=EntityKind.COLLECTIBLE;b.prototype.fill=function(a,b,e,f,g){this.kind=EntityKind.COLLECTIBLE;this.color=e;this.body=new PhysicsBody(a,new Vector2d(b/2,b/2));this.shrinkage=this.gravityFactor=0;this.triggerDistance=50;this.draw=
g||f.prototype.draw};b.prototype.onAnimate=function(a,b){var e=parrot,f=e.body.center.substract(this.body.center).getMagnitude();8>f?(this.collideAction(e),this.markForRemoval()):f<this.triggerDistance?this.body.gravitateTo(parrot.body.center,b):500<f&&-666!=this.kind&&this.markForRemoval()};b.prototype.collideAction=function(){aa.play("coin");addPoints(5)};return b}(Entity),Target=function(a){function b(b,d,e){a.call(this,b,d,16,15,[[15,16,2,1E3,[30*e,12]]]);this.kind=e;this.color=[F,W,P,T][e][2]}
__extends(b,a);b.prototype.onRemove=function(){var a=new Collectible(this.body.center,4,this.color||T[0],Bubble);world.addEntity(a,World.NO_COLLISION,World.FOREGROUND)};return b}(SpriteEntity),GroundEntity=function(){function a(a,c,d){this.isCollisionAware=this.isVisible=!0;this.groundheight=a;this.color=P[2];this.width=c||160;this.height=d||144}a.prototype.draw=function(a,c){a.save();a.fillStyle=this.color;a.beginPath();a.moveTo(-300,this.height);a.lineTo(-300,this.height-this.groundheight);a.lineTo(this.width,
this.height-this.groundheight);a.lineTo(this.width+1,this.height);a.closePath();a.fill();a.restore()};a.prototype.animate=noop;a.prototype.collidesWith=function(a){a=a.getLTWH();return this.groundheight+a[1]+a[3]>this.height?!0:!1};return a}(),World=function(){function a(){this.containers="nonCollidingEntities collideAllEntities collideGroundEntities backgroundEntities entities foregroundEntities".split(" ");this.entities=[];this.backgroundEntities=[];this.foregroundEntities=[];this.nonCollidingEntities=
[];this.collideGroundEntities=[];this.collideAllEntities=[];this.player=null;this.gravity=[0,.001];this.roundCount=0;this.pool={};this.pool[EntityKind.PARTICLE]=[];this.pool[EntityKind.BUBBLE]=[];this.pool[EntityKind.COLLECTIBLE]=[];a.instance=this}a.prototype.render=function(a,c){var d=this;0==this.roundCount%7&&this.groundElement.draw(a,d,c);this.containers.slice(3).forEach(function(e){e=d[e];for(var f=0;f<e.length;f++)e[f]&&e[f].isVisible&&e[f].draw(a,d,c)})};a.prototype.animate=function(a){var c=
this;this.resolveCollisions(a);this.containers.slice(3).forEach(function(d){d=c[d];for(var e=0;e<d.length;e++){var f=d[e];f.body&&300<f.body.center[0]-parrot.body.center[0]||(f.isAlive&&f.animate(c,a),f.isOnGround||f.applyGravity&&f.applyGravity(c.gravity,a))}});0==this.roundCount++%30&&this.clear()};a.prototype.clear=function(){var a=this,c=a.pool;this.containers.forEach(function(d){var e=a[d];3>a.containers.indexOf(d)?a[d]=e.filter(function(a){return a&&a.isMarked?(90<=a.kind&&c[a.kind].push(a),
!1):!0}):a[d]=e.filter(function(a){return a&&a.isMarked?!1:!0})})};a.prototype.resolveCollisions=function(a){a=this.collideGroundEntities;for(var c=a.length,d=this.groundElement,e,f=0;f<c;f++)(e=a[f])&&!e.isMarked&&!e.isOnGround&&d.collidesWith(e.body)&&e.collideGround(d);a=this.collideAllEntities;c=a.length;for(f=0;f<c;f++)if((e=a[f])&&!e.isMarked&&e.isAlive)for(j=f+1;j<c;j++)if((d=a[j])&&!d.isMarked&&d.isAlive&&!(300<d.body.center[0]-parrot.body.center[0])&&e.body.intersects(d.body)){e.collideAction(d);
d.collideAction(e);break}};a.prototype.addEntity=function(a,c,d){switch(c){case 0:this.nonCollidingEntities.push(a);break;case 1:this.collideGroundEntities.push(a);break;case 2:this.collideAllEntities.push(a);break;default:this.nonCollidingEntities.push(a)}switch(d){case 1:this.backgroundEntities.push(a);break;case 0:this.entities.push(a);break;case 2:this.foregroundEntities.push(a);break;default:this.entities.push(a)}};a.NO_COLLISION=0;a.COLLIDE_GROUND=1;a.COLLIDE_ALL=2;a.FOREGROUND=2;a.CENTER=0;
a.BACKGROUND=1;return a}(),Explosion=function(){function a(a,c){var d=c/16.666||1;this.params=a||{};this.params.mixin({count:[15,35],size:[1,4],strength:.3,offset:new Vector2d(0,0),colors:P,center:this.center=new Vector2d(0,0),life:[400,800],collisionType:World.NO_COLLISION,zIndex:World.BACKGROUND,gravityFactor:1,shrink:!1,particleType:Particle});this.zIndex=a.zIndex;this.collisionType=a.collisionType;var e=a.count;e instanceof Array&&(e=randBetween(e[0],e[1]));this.count=e=Math.ceil(e*d)}a.prototype.fire=
function(a,c){for(var d=this.params,e=d.particleType.kind,f=[],g=0;g<this.count;g++){if(90<=e&&c.pool[e].length){var h=c.pool[e].pop();h.isAlive=h.isVisible=!(h.isMarked=!1);h.fill(a.copy(),randBetween(d.size),d.colors.random(),randBetween(d.life),d.shrink)}else h=new d.particleType(a.copy(),randBetween(d.size),d.colors.random(),randBetween(d.life),d.shrink);f.push(h);h.isOnGround=!1;h.body.speed=Vector2d.random(d.strength).doAdd(d.offset);h.gravityFactor=randBetween(d.gravityFactor);c.addEntity(h,
this.collisionType,this.zIndex)}return f};return a}(),Emitters=function(){function a(a,b){this.kind=EntityKind.FIREEMITTER;this.entity=a;this.world=b;this.params={gravityFactor:[-.4,-.1],collisionType:World.NO_COLLISION,life:[600,1E3],count:[0,2],strength:.1,size:8,shrink:1,colors:F,particleType:Particle};this.exploder=new Explosion(this.params)}function b(a,b){this.kind=EntityKind.POISONEMITTER;this.entity=a;this.world=b;this.params={gravityFactor:[-.2,-.4],collisionType:World.NO_COLLISION,life:[600,
800],count:[0,1],strength:.1,size:2,shrink:2,colors:P,particleType:Bubble};this.exploder=new Explosion(this.params)}function c(a,b){this.entity=a;this.kind=EntityKind.WATEREMITTER;this.world=b;this.params={gravityFactor:[.1,.4],collisionType:World.COLLIDE_GROUND,life:[600,1E3],count:[0,2],offset:new Vector2d(.1,0),strength:.01,size:4,shrink:.3,colors:W};this.exploder=new Explosion(this.params)}function d(a,b){this.entity=a;this.kind=EntityKind.LIGHTNINGEMITTER;this.world=b;this.tracer=new Explosion({gravityFactor:0,
collisionType:World.NO_COLLISION,life:[200,500],count:[0,2],strength:.01,size:1,shrink:0,colors:T});this.exploder=new Explosion({gravityFactor:[-.1,.1],collisionType:World.COLLIDE_GROUND,life:[400,700],count:[0,1],strength:.1,size:[1,2],shrink:0,colors:T})}d.prototype.tick=function(){this.exploder.fire(this.entity.body.center,this.world);this.tracer.fire(this.entity.body.center,this.world)};b.prototype.tick=a.prototype.tick=c.prototype.tick=function(a,b){this.exploder.fire(this.entity.body.center,
this.world)};return{FireEmitter:a,WaterEmitter:c,PoisonEmitter:b,LightningEmitter:d}}(),Projectiles=function(a){function b(a,b,d,c){this.life=this._life=1500;this.body=new PhysicsBody(a.copy(),new Vector2d(d,d));this.body.speed.doAdd(b);this.body.friction=0;this.color=c}function c(d,c){a.call(this);b.call(this,d,[.2,0],3,F.random());this.kind=EntityKind.FIREBALL;this.emitter=new Emitters.FireEmitter(this,c);this.emitter.params.gravityFactor=[-.2,.1];this.emitter.params.strength=.05;this.emitter.params.count=
[0,1];this.resources.push(this.emitter)}function d(d,c){a.call(this);b.call(this,d,[.2,0],3,W.random());this.kind=EntityKind.WATERBOLT;this.emitter=new Emitters.WaterEmitter(this,c);this.emitter.params.count=[-1,1];this.resources.push(this.emitter)}function e(d,c){a.call(this);b.call(this,d,[.2,0],2,P[3]);this.kind=EntityKind.POISONBALL;this.emitter=new Emitters.PoisonEmitter(this,c);this.resources.push(this.emitter)}function f(d,c){a.call(this);b.call(this,d,[.2,0],2,T.random());this.kind=EntityKind.LIGHTNINGBOLT;
this.emitter=new Emitters.LightningEmitter(this,c);this.resources.push(this.emitter)}__extends(c,a);__extends(d,a);__extends(e,a);__extends(f,a);c.prototype.draw=function(a,b,d){var c=this.body.getLTWH();b=c[0];d=c[1];c=c[2];a.save();a.tr(b+c/2,d+c/2);a.fillStyle=this.color;a.fr(-c/2,-c/2,c,c);a.restore()};c.prototype.collideAction=function(a){10>a.kind&&(this.markForRemoval(),(new Explosion({gravityFactor:.7,colors:F,offset:this.body.speed.multiply(.5),zIndex:World.FOREGROUND,collisionType:World.COLLIDE_GROUND,
shrink:.6})).fire(this.body.center,world),aa.play("hit"))};d.prototype.collideAction=function(a){10>a.kind&&(this.markForRemoval(),(new Explosion({gravityFactor:.8,colors:W,offset:this.body.speed.multiply(.25),zIndex:World.FOREGROUND,collisionType:World.COLLIDE_GROUND,shrink:.8})).fire(this.body.center,world),aa.play("hit"))};d.prototype.draw=function(a,b,d){var c=this.body.getLTWH();b=c[0];d=c[1];var e=c[2],c=c[3];a.save();a.tr(b+e/2,d+c/2);a.rotate(this.body.rotation);a.strokeStyle=this.color;a.beginPath();
a.arc(0,0,this.body.corner.getMagnitude(),0,2*Math.PI,!1);a.stroke();a.restore()};e.prototype.collideAction=function(a){10>a.kind&&(this.markForRemoval(),(new Explosion({gravityFactor:-.3,colors:P,zIndex:World.FOREGROUND,collisionType:World.NO_COLLISION,shrink:2,particleType:Bubble,life:[150,500],strength:.3,count:[4,10]})).fire(this.body.center,world),aa.play("hit"))};e.prototype.draw=function(a,b,d){var c=this.body.getLTWH();b=c[0];d=c[1];var e=c[2],c=c[3];a.save();a.tr(b+e/2,d+c/2);a.rotate(this.body.rotation);
a.fillStyle=this.color;a.beginPath();a.arc(0,0,this.body.corner.getMagnitude(),0,2*Math.PI,!1);a.fill();a.restore()};f.prototype.collideAction=function(a){10>a.kind&&(this.markForRemoval(),(new Explosion({size:1,gravityFactor:[-.3,.3],colors:T,zIndex:World.FOREGROUND,collisionType:World.COLLIDE_GROUND,shrink:0,life:[150,500],strength:.3,count:[4,10]})).fire(this.body.center,world),aa.play("hit"))};f.prototype.onAnimate=function(a,b){this.body.center[1]+=(Math.random()-.5)/1300*b*155};f.prototype.draw=
function(a,b,d){var c=this.body.getLTWH();b=c[0];d=c[1];c=c[2];a.save();a.tr(b+c/2,d+c/2);a.fillStyle=this.color;a.fr(-c/2,-c/2,c,c);a.restore()};return{Fireball:c,Waterbolt:d,Poisonball:e,Lightningbolt:f}}(Entity),r=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60,1E3/60)}}();screen.msLockOrientation&&screen.msLockOrientation("landscape-primary")||screen.mozLockOrientation&&screen.mozLockOrientation("landscape-primary");
window.smb=document.getElementById("32s");var driveVector=new Vector2d(0,0),topV=new Vector2d(30,24),mid=new Vector2d(30,73),bottom=new Vector2d(30,118),slots=[topV,mid,bottom],shoot=function(a){parrot.isAlive&&(world.addEntity(new a(parrot.body.center,world),World.COLLIDE_ALL,World.CENTER),addPoints(-1),aa.play("shoot"))};
CMD={87:Function("targetVector=targetVector==bottom?mid:topV;"),83:Function("targetVector=targetVector==topV?mid:bottom"),72:Function("shoot(Projectiles.Fireball)"),74:Function("shoot(Projectiles.Waterbolt)"),75:Function("shoot(Projectiles.Poisonball)"),76:Function("shoot(Projectiles.Lightningbolt)"),32:Function("able([window.smb],false); aa.play('slowmo'); window.timeout = setTimeout(function(){CMD[7](window.smb)},10e3);timefactor=.25"),7:Function("btn","timefactor=1;window.timeout = setTimeout(function(){able([btn],true)},10e3)")};
command=function(a,b){if(window.gamerunning){if(b&&(!b.classList||!b.classList.contains("d")))CMD[a](b)}else startGame()};allButtons.forEach(function(a){a.onmousedown=a.ontouchstart=function(a){command(parseInt(this.id),this);a.preventDefault();a.handled=!0;return!1}});var ableAll=function(a){able(allButtons,a)};window.pts=0;window.hiscore=parseInt(localStorage.getItem("hiscore"))||0;points.textContent="High score: "+window.hiscore;window.postfix="";
var addPoints=function(a){window.pts+=a;switch(Math.floor(window.pts/50)){case 0:window.postfix="";break;case 1:window.postfix="!";break;case 2:window.postfix="!!";break;case 3:window.postfix="!1";break;case 4:window.postfix=", holy sh1t!";break;default:window.postfix=", ERMAGHERD!!2"}points.textContent="Points: "+window.pts+postfix},toggleVeil=function(a){veil.style.display=a?"block":"none"},switchGraphics=function(){window.cr=!window.cr;localStorage.setItem("cr",window.cr);crbutton.textContent=
"Graphics: "+(window.cr?"Low":"High")},soundOnOff=function(){window.mute=!window.mute;localStorage.setItem("mute",window.cr);mutebutton.textContent="Sounds: "+(window.mute?"Off":"On")},readInputs=function(){for(var a in readInputs.keys)+a&&a in CMD&&(command(+a,readInputs.keys[a]),delete readInputs.keys[a])},gameOver=function(){window.gamerunning=!1;window.hiscore=Math.max(window.hiscore,window.pts);localStorage.setItem("hiscore",window.hiscore);points.textContent="High score: "+window.hiscore;animate=
noop;loadGameEntities(s);toggleVeil(!0)},startGame=function(){window.gamerunning=!0;aa.play("start");window.timeout&&clearTimeout(window.timeout);window.pts=0;toggleVeil(!1);ableAll(!0);timefactor=1;animate=function(a){parrot.body.speed[1]=(targetVector[1]-parrot.body.center[1])*Math.max(a,16)/3E3;parrot.body.speed[0]=.05;world.animate(a);parrot.body.center[1]=clamp(parrot.body.center[1],topV[1],bottom[1])}};startbutton.onclick=startGame;crbutton.onclick=switchGraphics;mutebutton.onclick=soundOnOff;
readInputs.keys={};document.body.addEventListener("keydown",function(a){readInputs.keys[a.keyCode]=!0});document.body.addEventListener("keyup",function(a){readInputs.keys[a.keyCode]=!1});
var parrot,world,atlas,ground,targetVector,tree,enemy,loadGameEntities=function(a){world=new World;ground=new GroundEntity(15,3E3);world.groundElement=ground;parrot=new SpriteEntity(a,new Vector2d(0,73),16,12,[[16,12,6,400,[27,0]]]);parrot.collideAction=function(a){10>a.kind&&(aa.play("death"),this.markForRemoval())};parrot.onRemove=function(){for(var a=(new Explosion({colors:B,size:[1,5],count:[10,20],strength:.5,offset:this.body.speed.multiply(2),center:this.body.center,collisionType:World.COLLIDE_GROUND,
zIndex:World.FOREGROUND})).fire(this.body.center,world),a=a.filter(function(a){return 1.5<a.body.corner[0]}),b=0;b<a.length;b++){var c=a[b];c.restitution=.9;c.tracer=new Explosion({gravityFactor:0,collisionType:World.NO_COLLISION,life:[200,500],count:[0,2],strength:.01,size:1,shrink:0,colors:B.slice(2)});c.onAnimate=function(){this.tracer.fire(this.body.center,world)}}var d=function(){setTimeout(function(){a.every(function(a){return!a.isAlive})?gameOver():d()},100)};d()};targetVector=mid;for(var b=
function(a){a.kind-40==this.kind&&this.markForRemoval()},c=function(c,d){enemy=new Target(a,[c,d[1]],randBetween(0,4,!0));enemy.collideAction=b;world.addEntity(enemy,World.COLLIDE_ALL,World.CENTER)},d=0,e=100,f=1;5>f;){switch(f){case 1:c(100+d,slots.random());1E3<=d&&f++;break;case 2:var g=randBetween(0,3,!0),h=(g+1)%3;c(100+d,slots[g]);c(100+d,slots[h]);2E3<=d&&f++;break;case 3:c(100+d,slots[0]);c(100+d,slots[1]);c(100+d,slots[2]);e=Math.max(10,e-5);3E3<=d&&f++;break;default:g=new Collectible([d+
500,mid[1]],6,B[4],Bubble),g.kind=-666,g.collideAction=function(a){addPoints(50);a.markForRemoval()},world.addEntity(g,World.NO_COLLISION,World.FOREGROUND),f++}d+=e}world.addEntity(parrot,World.COLLIDE_ALL,World.CENTER)},s=new SpriteSheet(imglol,loadGameEntities),animate=noop,ctx=miniCanvas.getContext("2d");ctx.webkitImageSmoothingEnabled=!1;ctx.imageSmoothingEnabled=!1;translation=0;
var render=function(a){parrot&&world&&(translation=-parrot.body.center[0]+30,ctx.save(),ctx.tr(translation,0),.9<timefactor&&(ctx.fillStyle=P[0],ctx.fr(-translation,0,miniCanvas.width,miniCanvas.height-15)),world.render(ctx,a),ctx.restore())},timefactor=1,gameLoop=function(a){a=a||(gameLoop.lastTime||0)+1E3/60;if(gameLoop.lastTime){var b=Math.min(a-gameLoop.lastTime,70)*timefactor;r(gameLoop);readInputs(b);animate(b);render(b);gameLoop.lastTime=a}else gameLoop.lastTime=a,r(gameLoop)};gameLoop();