var b="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)},e="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function f(){f=function(){};e.Symbol||(e.Symbol=k)}var k=function(){var a=0;return function(c){return"jscomp_symbol_"+(c||"")+a++}}();
function l(){f();var a=e.Symbol.iterator;a||(a=e.Symbol.iterator=e.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&b(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return m(this)}});l=function(){}}function m(a){var c=0;return n(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})}function n(a){l();a={next:a};a[e.Symbol.iterator]=function(){return this};return a}
function q(a){if(!(a instanceof Array)){l();f();l();var c=a[Symbol.iterator];a=c?c.call(a):m(a);for(var d=[];!(c=a.next()).done;)d.push(c.value);a=d}return a}var r=document.createElement("canvas"),t=r.getContext("2d"),u=r.width=720,v=r.height=.8*u,w=2*Math.PI,y=x(),z=-1,A=[300,240,170,60,0],B=localStorage.D?JSON.parse(localStorage.D):[],C=document.createElement("style");C.innerHTML="body{text-align:center;background:#000}canvas{cursor:crosshair;\noutline:navy solid 15px}.start{cursor:pointer;position:absolute;bottom:50px;\nleft:calc(50% - 125px);width:200px;color:#FFF;padding:10px 25px;font-size:25px;\nfont-family:monospace;outline:#fff solid 5px}.start:hover{color:#222;\noutline:#222 solid 5px}.container{margin:30px auto;position:relative}";
document.head.appendChild(C);var D=document.createElement("div");D.classList.add("container");var E=document.createElement("div");E.classList.add("start");E.innerText="New Game";E.addEventListener("click",function(){z=-1;F=G({},H());E.setAttribute("hidden","true");I();r.focus();J(F)});document.body.appendChild(D);D.appendChild(r);D.appendChild(E);
function x(){var a={x:0,y:0};r.addEventListener("mousemove",function(c){return Object.assign(a,{x:c.pageX-r.offsetLeft,y:c.pageY-r.offsetTop})});return a}var K={};window.addEventListener("keyup",function(a){return delete K[a.which]});window.addEventListener("keydown",function(a){return K[a.which]=!0});
function L(a,c){for(var d=[],g=1;g<arguments.length;++g)d[g-1]=arguments[g];return function(c){for(var g=[],h=0;h<arguments.length;++h)g[h-0]=arguments[h];return a.apply(null,[].concat(q(d),q(g)))}}function G(a,c){for(var d=[],g=1;g<arguments.length;++g)d[g-1]=arguments[g];return Object.assign.apply(Object,[{},a].concat(q(d)))}function M(a,c){return Math.random()*(c-a)+a}function N(a,c){var d=a.x-c.x,g=a.y-c.y;return Math.sqrt(d*d+g*g)<a.a+c.a}
function I(){z++;z in A||(z=0);C.innerHTML+="canvas {filter: contrast(175%) brightness(105%) hue-rotate("+A[z]+"deg); }"}function O(a){if(5>B.length)B.push(a);else{B.sort(function(a,c){return a<c});B.reverse();for(var c=0;c<B.length;++c)if(B[c]<a){B.splice(c,0,a);break}}B.sort(function(a,c){return a<c});B.splice(5);localStorage.setItem("highScore",JSON.stringify(B))}var P=L(G,{x:0,y:0,j:0,l:0}),Q=L(P,{a:0,color:"#FFF",rotation:0});
function R(a){a=void 0===a?4:a;t.save();t.lineWidth=40;t.strokeStyle=4<=a?"rgba(255,255,255,.2)":"rgba(255,255,255,.05)";t.beginPath();t.arc(u/2,v/2,180,Math.PI+.4,w-.4);t.stroke();t.strokeStyle=3<=a?"rgba(255,255,255,.2)":"rgba(255,255,255,.05)";t.beginPath();t.arc(u/2,v/2,130,Math.PI+.4,w-.4);t.stroke();t.strokeStyle=2<=a?"rgba(255,255,255,.2)":"rgba(255,255,255,.05)";t.beginPath();t.arc(u/2,v/2,80,Math.PI+.4,w-.4);t.stroke();t.fillStyle=0<a?"rgba(255,255,255,.2)":"rgba(255,255,255,.05)";t.beginPath();
t.arc(u/2,v/2,50,0,w);t.fill();t.restore()}function S(){t.save();t.fillStyle="#FFF";t.font="45px monospace";t.fillText("Game Over!",u/2,v/2-140);t.font="20px monospace";t.fillText("Connection lost! You are now offline...",u/2,v/2-100);t.fillText("High Scores:",u/2,v/2-60);var a=-30;B.map(function(c,d){0<d&&(a+=30);t.fillText(c+" pts",u/2,v/2+a)});t.restore()}var T=L(Q,{speed:4,h:0,a:20,i:4,f:!1,color:"rgb(72,255,206)",C:"rgba(72,255,206,.1)"});
function U(a){t.save();t.translate(a.x,a.y);t.lineWidth=2.5;t.strokeStyle=a.C;t.beginPath();t.moveTo(1.5*a.a,0);t.lineTo(u,0);t.stroke();t.moveTo(1.5*-a.a,0);t.lineTo(-u,0);t.stroke();t.beginPath();t.moveTo(0,1.5*a.a);t.lineTo(0,v);t.stroke();t.beginPath();t.moveTo(0,1.5*-a.a);t.lineTo(0,-v);t.stroke();t.strokeStyle=a.color;var c=a.a-a.a/4;t.rotate(a.rotation);t.beginPath();t.moveTo(c,0);t.lineTo(-c,c);t.lineTo(-c-c/2,0);t.lineTo(-c,-c);t.lineTo(c,0);t.stroke();t.restore()}
function V(a){if(K[38]||K[87])a.l=-a.speed;if(K[40]||K[83])a.l=a.speed;if(K[37]||K[65])a.j=-a.speed;if(K[39]||K[68])a.j=a.speed;a.x+=a.j;a.y+=a.l;a.j*=.96;a.l*=.96;0>=a.x-a.a&&(a.x=a.a);0>=a.y-a.a&&(a.y=a.a);a.x+a.a>=u&&(a.x=u-a.a);a.y+a.a>=v&&(a.y=v-a.a);a.rotation=Math.atan2(y.y-a.y,y.x-a.x);a.f&&(a.G=!0,a.f=!1,a.i--)}var W=L(Q,{speed:6,a:5,target:P(),g:!1,color:"rgb(0, 255, 255)"}),X=L(Q,{a:18,f:!1,target:P(),g:!1,speed:M(1.5,3),color:"hsl(0, 50%, 50%)"});
function aa(a){var c=M(0,u),d=M(0,v);return X({x:.5<M(0,1)?c+u:c-u,y:.5<M(0,1)?d+v:d-v,target:a})}var ba=L(Q,{B:18,speed:1.8,a:32,v:!0,f:!1,target:P(),g:!1,color:"hsl(0, 50%, 50%)"});function ca(a){t.save();t.lineWidth=3;t.translate(a.x,a.y);t.rotate(a.rotation);t.strokeStyle="hsl("+a.x%360+", 80%, 35%)";t.fillStyle="hsl("+a.x%360+", 80%, 35%)";var c=a.a;t.beginPath();t.moveTo(c,0);t.lineTo(-c,c);t.lineTo(-c-c/2,0);t.lineTo(-c,-c);t.lineTo(c,0);a.f?(t.fill(),a.f=!1):t.stroke();t.restore()}
function da(a){var c=a.target.x-a.x,d=a.target.y-a.y,g=Math.sqrt(c*c+d*d);g<a.a?a.g=!0:(c/=g,d/=g,a.x+=c*a.speed,a.y+=d*a.speed,a.rotation=Math.atan2(d,c),a.f&&--a.B,1>a.B&&(a.v=!1))}function ea(a){var c=M(0,u),d=M(0,v);return ba({x:.5<M(0,1)?c+u:c-u,y:.5<M(0,1)?d+v:d-v,target:a})}var Y=L(Q,{alpha:1,count:8,a:1,u:[],color:"red",ended:!1,A:3});function fa(a){for(var c=[],d=a.count,g=a.a,h=0;h<d;++h){var p=Q({x:a.x,y:a.y,alpha:1,j:g*Math.cos(w*h/d),l:g*Math.sin(w*h/d),a:a.A});c.push(p)}return c}
function ha(a){a.u.length||(a.u=fa(a));a.u.map(function(c){c.x+=c.j;c.y+=c.l;t.save();t.translate(c.x,c.y);t.strokeStyle="hsla(0,80%,80%,"+a.alpha+")";t.beginPath();t.arc(0,0,c.a,0,w);t.stroke();t.restore()});a.alpha&&(a.alpha-=.03,0>a.alpha&&(a.ended=!0))}
function H(){var a=T({x:u/2,y:v/2}),c=document.createElement("canvas"),d=c.getContext("2d");c.width=u;c.height=v;document.body.appendChild(c);d.fillStyle="hsl(220, 60%, 50%)";d.fillRect(0,0,u,v);d.fillStyle="hsla(0, 0%, 0%, 0.1)";d.fillRect(0,0,u,v);for(var g=0;g<u;g++)for(var h=0;h<v;h++)d.fillStyle="hsla(0, 0%, "+M(0,100)+"%, 0.02)",d.fillRect(g,h,1,1);for(g=0;g<v;g+=1)d.fillStyle=0===g%2?"hsla(0, 0%, 0%, 0.1)":"hsla(0, 0%, 100%, 0.05)",d.fillRect(0,g,u,1);g=d.createRadialGradient(u/2,v/2,0,u/2,
v/2,v);g.addColorStop(0,"hsla(0, 0%, 100%, .3)");g.addColorStop(1,"hsl(0, 0%, 0%)");d.globalCompositeOperation="overlay";d.fillStyle=g;d.fillRect(0,0,u,v);d=d.getImageData(0,0,u,v);document.body.removeChild(c);return G({},{b:a,m:[],o:[],c:null,F:8,w:d,count:0,s:[]})}var F=H();
function J(a){0<a.b.i?window.requestAnimationFrame(L(J,a)):(E.removeAttribute("hidden"),O(a.b.h),window.requestAnimationFrame(function(){return S()}));t.putImageData(a.w,0,0,0,0,u,v);R(a.b.i);t.save();t.font="12px monospace";t.fillStyle="rgba(255,255,255,1)";t.fillText(a.b.h+" pts",u-50,v-20);t.restore();a.count++;a.count%999&&a.o.length<a.F&&a.o.push(aa(a.b));if(1200===a.b.h||1600<a.b.h&&0===a.b.h%1600&&!a.c)a.c=ea(a.b);a.s=a.s.map(function(a){return ha(a),a}).filter(function(a){return!a.ended});
a.o=a.o.map(function(a){var d=a.target.x-a.x,c=a.target.y-a.y,p=Math.sqrt(d*d+c*c);p<a.a?a.g=!0:(d/=p,c/=p,a.x+=d*a.speed,a.y+=c*a.speed,a.rotation=Math.atan2(c,d));return a}).map(function(d){N(d,a.b)&&(d.g=!0,a.b.f=!0);return d}).filter(function(a){return!a.g}).filter(function(d){d.f&&a.s.push(Y({x:d.x,y:d.y}));return!d.f});a.m=a.m.map(function(a){var d=a.target.x-a.x,c=a.target.y-a.y,p=Math.sqrt(d*d+c*c);p<a.a?a.g=!0:(d/=p,c/=p,a.x+=d*a.speed,a.y+=c*a.speed,a.rotation=Math.atan2(c,d));return a}).filter(function(a){return!a.g});
a.m.find(function(d){var c=a.o.find(function(a){return N(a,d)});return c?(c.f=!0,a.b.h+=50,!0):!1});V(a.b);a.m.map(function(a){t.save();t.translate(a.x,a.y);t.rotate(a.rotation);t.lineWidth=1;t.strokeStyle=a.color;a=a.a;t.beginPath();t.moveTo(a,0);t.lineTo(-a,a);t.lineTo(-a-a/2,0);t.lineTo(-a,-a);t.lineTo(a,0);t.stroke();t.restore()});a.o.map(function(a){t.save();t.translate(a.x,a.y);t.rotate(a.rotation);t.fillStyle=a.color;a=a.a;var c=a/4;t.beginPath();t.moveTo(0,0);t.lineTo(-a/2,-a/2-c);t.lineTo(a,
0);t.lineTo(a,0);t.lineTo(-a/2,a/2+c);t.closePath();t.fill();t.restore()});U(a.b);if(a.c){var c=a.m.find(function(c){return N(c,a.c)});c&&(a.c.f=!0,c.g=!0);da(a.c);ca(a.c);N(a.b,a.c)&&(a.b.i-=.1);a.c.v||(a.b.h+=400,a.s.push(Y({x:a.c.x,y:a.c.y,a:3,count:10,A:6})),a.c=null,I())}}t.textAlign="center";t.textBaseline="middle";t.globalCompositeOperation="lighter";var Z=H();t.save();t.putImageData(Z.w,0,0,0,0,u,v);R(Z.b.i);t.fillStyle="#FFF";t.strokeStyle="#FFF";t.font="45px monospace";
t.fillText("Connection Defender",u/2,v/2-80);t.font="25px monospace";t.fillText("W,A,S,D or Arrow Keys to move.",u/2,v/2);t.fillText("Mouse to aim.",u/2,v/2+40);t.fillText("Click to shoot.",u/2,v/2+80);t.restore();I();r.addEventListener("click",function(){F.b.i&&F.m.push(W({x:F.b.x,y:F.b.y,target:y}))});