(function(){function G(){function a(){if(B)c.fillStyle="#000",c.fillText("Click to resume",505,384),p=k();else{for(q=0;k()>p&&10>q;)l.update(e,f,C,d),p+=m,q++;l.c(c,e,d)}requestAnimationFrame(a)}var b=document.getElementById("mc"),c=b.getContext("2d");c.mozImageSmoothingEnabled=false;
c.webkitImageSmoothingEnabled=false;c.msImageSmoothingEnabled=false;c.imageSmoothingEnabled=false;c.Fb=!1;c.Hb=!1;c.Gb=!1;c.Eb=!1;var e={width:b.width,height:b.height};this.state="LOADING";this.vb=new t([500,500]);this.f=new H;this.t=new I(this,e);this.h=[];this.h=this.h.concat(new u(200+r(0,20),251,0,"fg",2));this.h=this.h.concat(new u(700+r(0,
20),251,0,"fg",2));this.h=this.h.concat(new u(100,367,3,"wd",0));this.h=this.h.concat(new u(200+r(0,20),575,1,"eg",1));this.h=this.h.concat(new u(800+r(0,20),575,1,"eg",1));this.h=this.h.concat(new u(-50,705,2,"ig",1));this.r=[];var d=[],d=d.concat(new s(10,150,10,450,"wd ww fg fb eg ro".split(" "))),d=d.concat(new s(1E3,150,10,450,"wd ww fg fb eg ro".split(" "))),d=d.concat(new s(345,150,10,130,["fg"])),d=d.concat(new s(672,150,10,130,["fg"])),d=d.concat(new s(500,450,10,130,["eg"])),d=d.concat(new s(595,
450,10,130,["eg"])),d=d.concat(new s(-80,600,10,130,["ig"])),d=d.concat(new s(1080,600,10,130,["ig"]));this.Ga=0;n=new J;n.add("pickup",2,[[0,,.01,.4394,.3103,.8765,,,,,,.3614,.5278,,,,,,1,,,,,.5]]);n.add("jump",1,[[0,,.1625,,.159,.2246,,,,,,,,.0471,,,,,1,,,.1,,.29]]);n.add("pewpew",3,[[2,,.2742,.0215,.0863,.6068,.2,-.196,,,,,,.5091,-.515,,,,1,,,,,.29]]);n.add("cheep",4,[[2,.1602,.01,.4203,.6306,.5952,,-.129,.04,.19,.75,.5614,.06,-.7285,.9046,-.595,.9816,-.5187,.9028,.6024,.6813,.521,-.0292,.5]]);
this.s=[];this.s=this.s.concat(this.t);this.s=this.s.concat(new K(this,e));var f=[];this.A=[];var C=[],C=C.concat(new h(-60,742,1084,20,{})),f=f.concat(new h(-30,730,1054,48,{})),f=f.concat(new h(-30,580,533,4,{bottom:!0})),f=f.concat(new h(600,580,500,4,{bottom:!0})),f=f.concat(new h(-30,430,1054,4,{bottom:!0})),f=f.concat(new h(-30,280,372,4,{bottom:!0})),f=f.concat(new h(402,280,220,4,{bottom:!0})),f=f.concat(new h(682,280,382,4,{bottom:!0})),f=f.concat(new h(0,130,1024,4,{})),f=f.concat(new h(64,
680,32,5,{left:!0,right:!0,bottom:!0})),f=f.concat(new h(32,630,32,5,{left:!0,right:!1,bottom:!0})),f=f.concat(new h(0,584,32,5,{bottom:!1})),f=f.concat(new h(928,680,32,5,{left:!0,right:!0,bottom:!0})),f=f.concat(new h(960,630,32,5,{left:!1,right:!0,bottom:!0})),f=f.concat(new h(992,584,32,5,{bottom:!1})),f=f.concat(new h(64,530,32,5,{left:!0,right:!0,bottom:!0})),f=f.concat(new h(32,480,32,5,{left:!0,right:!1,bottom:!0})),f=f.concat(new h(0,434,32,5,{bottom:!1})),f=f.concat(new h(928,530,32,5,{left:!0,
right:!0,bottom:!0})),f=f.concat(new h(960,480,32,5,{left:!1,right:!0,bottom:!0})),f=f.concat(new h(992,434,32,5,{bottom:!1})),f=f.concat(new h(64,380,32,5,{left:!0,right:!0,bottom:!0})),f=f.concat(new h(32,330,32,5,{left:!0,right:!1,bottom:!0})),f=f.concat(new h(0,284,32,5,{bottom:!1})),f=f.concat(new h(928,380,32,5,{left:!0,right:!0,bottom:!0})),f=f.concat(new h(960,330,32,5,{left:!1,right:!0,bottom:!0})),f=f.concat(new h(992,284,32,5,{bottom:!1}));this.pa=[];for(b=100;900>b;b+=33)this.pa.push(new h(b,
720,32,3,{}));this.s=this.s.concat(f);var l=this;this.ib();this.Sa=new g(12,30,[{a:0,b:72}]);this.Ta=new g(12,30,[{a:12,b:72}]);this.Ua=new g(12,30,[{a:48,b:72}]);this.Da=new g(24,14,[{a:97,b:58}]);this.cb=new g(7,3,[{a:83,b:62}]);this.eb=new g(7,3,[{a:90,b:62}]);this.va=new g(60,4,[{a:32,b:67}]);this.wb=new g(7,8,[{a:29,b:94}]);this.xb=new g(6,8,[{a:36,b:94}]);this.hb=new g(24,21,[{a:24,b:72}]);this.R=new g(50,25,[{a:121,b:46}]);this.ea=new g(14,8,[{a:0,b:8,duration:500},{a:14,b:8,duration:500}]);
this.Cb=new g(14,8,[{a:8,b:16}]);this.D=new g(4,8,[{a:0,b:16}]);this.nb=new g(4,8,[{a:4,b:16}]);this.lb=new g(7,8,[{a:0,b:32}]);this.gb=new g(7,8,[{a:0,b:0,duration:400}]);this.Fa=new g(7,8,[{a:81,b:34},{a:89,b:34},{a:83,b:53}]);this.na=new g(13,6,[{a:97,b:52},{a:97,b:49}]);this.ab=new g(13,13,[{a:97,b:45}]);this.J=0;var m=1E3/60,p=k(),q=0;a()}function I(a,b){this.G=a;this.height=54;this.width=30;this.x=b.width/2;this.y=b.height-50;this.f=new H;this.speed=3;this.i=this.e=0;this.B=.9;this.q=!1;this.C=
!0;this.F=!1;this.fb=.3;this.d=this.ma=!1;this.ca=new g(15,27,[{a:60,b:72}]);this.Q=new g(15,27,[{a:60,b:72,duration:100},{a:129,b:72,duration:100}]);this.tb=new g(24,27,[{a:118,b:0}]);this.ub=new g(20,29,[{a:142,b:0,duration:50}]);this.state="w"}function p(a,b,c,e,d,f,g){a=new L(a,b,c,e,d,f,g);m.r=m.r.concat(a);return a}function L(a,b,c,e,d,f,h){this.width=32;this.height=64;this.x=a;this.y=b;this.type=c;this.H=1E3;this.d=e||!1;this.bb=d||!1;this.jb=f||!1;this.kb=h||!1;this.sb=k();this.g=!1;this.i=
this.e=0;this.speed=1;this.B=.9;this.I=null;this.U=0;this.V=5;this.ka=this.ja=-1;this.O={};this.Z=!1;switch(this.type){case 1:this.H=3500;this.y=this.y-this.height-1;this.speed=3;this.I=new g(16,32,[{a:0,b:40,duration:100},{a:15,b:40,duration:100}]);break;case 5:case 2:this.H=3500;this.speed=4;this.I=new g(7,7,[{a:81,b:34}]);this.y-=18;break;case 3:this.speed=2;case 6:this.H=2E3;this.speed=4;this.I=new g(8,7,[{a:88,b:34}]);this.y-=18;break;case 4:this.H=0;this.speed=1;this.I=new g(12,29,[{a:171,b:0}]);
this.y-=30;this.width=24;this.O={bottom:!1,left:!1,right:!1};break;case 7:this.H=3500,this.speed=5,this.I=new g(7,7,[{a:83,b:53}]),this.y-=18}}function u(a,b,c,e,d){this.width=32;this.height=64;this.x=a;this.y=b;this.type=c;this.o=k();this.now=null;this.d=.5>Math.random();this.g=!1;this.P=null;this.Wa=e;this.speed=d||2;this.ta=null;this.state="w";this.j=this.Ka=this.k=this.l=null;this.p=new t([800,800,200]);switch(this.type){case 0:this.l=new g(12,15,[{a:33,b:33,duration:200},{a:45,b:33,duration:200}]);
this.k=new g(12,15,[{a:57,b:33,duration:50},{a:69,b:33,duration:50}]);this.height=30;break;case 1:this.l=new g(18,3,[{a:62,b:49,duration:500},{a:80,b:49,duration:500}]);this.speed=1;this.k=new g(18,13,[{a:133,b:32,duration:400}]);for(a=0;7>a;a++)this.k.frames.push({a:97,b:32,duration:200}),this.k.frames.push({a:151,b:32,duration:200});this.k.frames.push({a:133,b:32,duration:400});this.k.frames.push({a:133,b:32,duration:100});this.Ka=new g(18,13,[{a:115,b:32,duration:100}]);this.height=6;this.width=
35;this.p=new t([600,800,4E3,400]);this.p.w=r(0,3);break;case 2:this.l=new g(13,12,[{a:31,b:53,duration:200},{a:44,b:53,duration:200}]);this.k=new g(13,12,[{a:57,b:53,duration:200},{a:70,b:53,duration:200}]);this.height=24;this.width=26;break;case 3:console.log("here"),this.ia=this.X=!1,this.M=0,this.oa=[[0,10],[2,20],[2,20],[2,20],[1,20],[0,20],[0,20],[0,20],[-1,20],[-2,20],[-2,20],[-2,20]],this.l=new g(16,32,[{a:42,b:0},{a:58,b:0},{a:74,b:0},{a:90,b:0}])}}function s(a,b,c,e,d){this.width=c;this.height=
e;this.x=a;this.y=b;this.Va=d||[]}function K(a,b){this.G=a;this.width=36;this.height=52;this.x=b.width/2;this.y=77;this.speed=3;this.e=0;this.B=.6;this.S=this.d=!1;this.v=0;this.qa=10;this.ca=new g(18,26,[{a:75,b:73,duration:200},{a:93,b:73,duration:200}]);this.Q=new g(18,26,[{a:75,b:73,duration:200},{a:111,b:73,duration:200}])}function M(a,b){this.height=this.width=14;this.x=a;this.y=b;this.e=0;this.i=r(1,2)/2;this.B=.7;this.toggle=.5>Math.random();this.v=0;this.Ja=r(20,60);this.g=this.T=!1;this.Ma=
new g(7,8,[{a:0,b:0,duration:400},{a:21,b:0,duration:400}]);this.La=new g(7,8,[{a:0,b:0,duration:400},{a:7,b:0,duration:400},{a:14,b:0,duration:400}])}function h(a,b,c,e,d){this.width=c;this.height=e;this.x=a;this.y=b;this.O={bottom:d.bottom||!1,left:d.left||!1,right:d.right||!1};this.$=!0}function J(){this.ba={};this.aa=!0}function H(){var a={};window.addEventListener("keydown",function(b){a[b.keyCode]=!0});window.addEventListener("keyup",function(b){a[b.keyCode]=!1});this.n=function(b){return!0===
a[b]};this.fa=function(b){for(var c=Object.keys(a),e=0;e<c.length;e++)if(!0===a[c[e]])if(b){if(w.N())return w.reset(),!0}else if(x.N())return x.reset(),!0;return!1};this.m={ya:37,za:39,Ba:38,Oa:40,Aa:32,Ca:90,Ra:88,Na:67,Pa:77,Qa:80}}function g(a,b,c){this.width=a;this.height=b;this.frame=0;this.frames=c;this.wa=k()}function t(a){this.timestamp=k();this.la=a||[];this.w=0}function N(a,b){var c=a.x+a.width/2-(b.x+b.width/2),e=a.y+a.height/2-(b.y+b.height/2),d=a.width/2+b.width/2,f=a.height/2+b.height/
2,g=null;Math.abs(c)<d&&Math.abs(e)<f&&(d-=Math.abs(c),f-=Math.abs(e),d>=f?0<e?(a.F=!1,g="t",b.O.bottom?g=null:a.y+=f):b.O.bottom&&a.F?g=null:(g="b",a.y-=f):0<c?b.O.right?g=null:(g="l",a.x+=d):b.O.left?g=null:(g="r",a.x-=d));return g}function r(a,b){return Math.floor(Math.random()*(b-a+1))+a}function k(){return Date.now()}function l(a,b){return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.height+a.y>b.y?!0:!1}var m=null,D=[],q=!1,B=!1,n=null,y=0,z=0,A=0,E,F=1*new Date,O=document.getElementById("fps");
setInterval(function(){O.innerHTML=A.toFixed(1)+" fps"},1E3);t.prototype={start:function(){this.timestamp=k()},check:function(){k()-this.timestamp>this.la[this.w]&&this.next()},next:function(){this.start();this.w++;this.w>=this.la.length&&(this.w=0)},W:function(){this.check();return this.w},N:function(){return k()-this.timestamp>this.la[this.w]?!0:!1},reset:function(){this.timestamp=k();this.w=0}};var x=new t([200]),v=new t([200]),w=new t([2E3]);g.prototype={c:function(a,b,c,e){this.frame>=this.frames.length&&
(this.frame=0);e?(a.save(),a.translate(a.canvas.width,0),a.scale(-1,1),a.drawImage(D[0],this.frames[this.frame].a,this.frames[this.frame].b,this.width,this.height,a.canvas.width-b-2*this.width,c,2*this.width,2*this.height),a.restore()):a.drawImage(D[0],this.frames[this.frame].a,this.frames[this.frame].b,this.width,this.height,b,c,2*this.width,2*this.height)},update:function(){var a=k();this.frames[this.frame].duration&&a-this.wa>this.frames[this.frame].duration&&(this.wa=a,this.mb())},u:function(a){this.frame=
a},mb:function(){this.frame++;this.frame>=this.frames.length&&(this.frame=0)},reset:function(){this.frame=0;this.wa=k()}};J.prototype={add:function(a,b,c){this.ba[a]=[];c.forEach(function(c,d){this.ba[a].push({da:0,count:b,Ha:[]});for(var f=0;f<b;f++){var g=new Audio;g.src=jsfxr(c);this.ba[a][d].Ha.push(g)}},this)},play:function(a){this.aa||(a=this.ba[a],a=1<a.length?a[Math.floor(Math.random()*a.length)]:a[0],a.Ha[a.da].play(),a.da<a.count-1?a.da++:a.da=0)}};h.prototype={update:function(){},c:function(){}};
M.prototype={update:function(a,b,c){if(this.T||this.g){if(this.Ma.update(),5>this.x||this.x>a.width-5)this.T=this.g=!0}else{this.e=this.toggle?this.e+1:this.e-1;this.v++;this.v>this.Ja&&(this.toggle=!this.toggle,this.v=0,this.Ja=r(40,60));this.e*=this.B;this.x+=this.e;this.y+=this.i;for(var e=0;e<b.length;e++)l(this,b[e])&&(5>this.x||this.x>a.width-5?this.g=!0:this.T||this.g||y++,this.T=!0);this.La.update()}!this.g&&l(this,c)&&(this.g=!0,n.play("pickup"),z++,31<z&&(w.reset(),m.state="END"),this.T&&
y--)},c:function(a){this.T?this.Ma.c(a,this.x,this.y):this.La.c(a,this.x,this.y,0>this.e)}};K.prototype={update:function(a){this.S||(this.d?this.e>-this.speed&&this.e--:this.e<this.speed&&this.e++,this.e*=this.B,this.x+=this.e,this.x>a.width-100&&(this.d=!0,this.e=0),100>this.x&&(this.d=!1,this.e=0));!this.S&&0>this.qa&&100<r(1,1E3)&&(this.S=!0,this.v=r(100,200),this.qa=40,this.G.A=this.G.A.concat(new M(this.x,this.y)),this.ca.update());0<this.v&&this.S?(this.v--,this.ca.update(),0>=this.v&&(this.S=
!1,this.Q.u(0))):(this.qa--,this.Q.update())},c:function(a){this.S?this.ca.c(a,this.x,this.y,!this.d):this.Q.c(a,this.x,this.y,!this.d)}};s.prototype={Ea:function(a){return-1<this.Va.indexOf(a.toLowerCase())?!0:!1}};u.prototype={update:function(a,b,c,e){for(var d=0;d<a.length;d++)if(l(this,a[d])&&a[d].Ea(this.Wa)&&this.P!==a[d]){this.d=!this.d;this.P=a[d];if(2===this.type)switch(this.state){case "hb":this.state="pb";this.speed=1;this.j=p(this.d?this.x-25:this.x+this.width+1,this.y-4,4,this.d,!1,!1,
!1);break;case "pb":case "dj":null===this.j||this.j.g||(this.j.g=!0,this.j=null);this.state="w";this.speed=1;break;case "t":this.x=this.d?-60:1030,this.state="w",this.speed=1}break}switch(this.type){case 0:this.Ab(a,b,c);break;case 1:this.zb(a,b,c);break;case 2:this.Bb(a,b,c,e);break;case 3:this.yb(a,b,c)}},yb:function(a,b,c){this.ua(["6"],["2","3","5","6","7"],c)&&(this.state="d");this.now=k();switch(this.state){case "d":this.y+=3;1E3<this.y&&this.reset();break;case "w":this.l.u(0);if(!this.g){if(this.now-
this.o>this.oa[this.M][1])for(this.x=this.d?this.x-2:this.x+2,this.y-=this.oa[this.M][0],this.M++,this.M>=this.oa.length&&(this.M=0,this.L++,this.ia&&(this.d=!this.d,this.ia=!1),this.Y(b,800)&&(this.state="l",this.L=0,this.o=this.now)),this.o=this.now,b=0;b<a.length;b++)l(this,a[b])&&a[b].Ea("wd")&&this.P!==a[b]&&(this.P=a[b],this.ia=!0);13<this.L&&(this.state="s",this.o=this.now)}break;case "s":this.Y(b,800)?(this.state="l",this.L=0,this.o=this.now):1300<this.now-this.o?(this.o=this.now,this.state=
"w",this.L=0,this.X=!1):900<this.now-this.o?this.l.u(1):300<this.now-this.o&&this.l.u(0);break;case "l":this.l.u(2);500<this.now-this.o&&(this.state="a",this.o=this.now,this.X=!1);break;case "a":this.X||(n.play("cheep"),this.ga(),this.X=!0,this.l.u(3)),1E3<this.now-this.o&&(this.o=this.now,this.state="w",this.L=11,this.X=!1)}},Ab:function(a,b,c){this.ua(["7"],["2","3","5","6","7"],c)&&(this.state="d");switch(this.state){case "d":this.y+=3;1E3<this.y&&this.reset();break;case "w":this.xa();this.l.update();
switch(this.p.W()){case 1:case 2:this.Y(b,100)&&(this.state="a",this.p.reset())}break;case "a":switch(this.k.update(),this.p.W()){case 1:this.ga(),this.state="w",this.p.reset()}}},ua:function(a,b,c){for(var e=0;e<c.length;e++)if(!c[e].g&&l(this,c[e])&&(-1<b.indexOf(""+c[e].type)&&(c[e].g=!0),-1<a.indexOf(""+c[e].type)))return!0;return!1},Bb:function(a,b,c,e){this.xa();this.l.update();this.k.update();this.ua(["5"],["2","3","5","6","7"],c)&&(this.state="d");switch(this.state){case "d":this.y+=3;1E3<
this.y&&this.reset();break;case "w":b=!1;l(this,e[12])&&e[12].$&&(b=!0);for(a=0;a<c.length;a++)c[a].g||4!==c[a].type||l(this,c[a])&&(b=!0);b&&(this.state="hb",this.speed=4,this.d=!this.d,this.P=null,this.ta=12,e[12].$=!1,150>this.x||840<this.x)&&(this.state="t");break;case "pb":b=!1;if(null===this.j||this.j.g)b=!0;var d=["2","3","5","6","7"];if(!b){for(a=0;a<c.length;a++)c[a].g||4===c[a].type&&this.j!==c[a]&&l(this.j,c[a])&&(b=!0),-1<d.indexOf(""+c[a].type)&&l(this.j,c[a])&&(c[a].g=!0,5===c[a].type&&
(this.j.g=!0,this.j.Z&&(e[12].$=!0)));for(c=0;c<e.length;c++)l(this,e[c])&&c===this.ta&&(b=this.j.Z=!0)}b&&(this.state="dj",this.speed=4,this.ta=null,this.d=!this.d,this.j=this.P=null)}},zb:function(a,b){this.xa();switch(this.state){case "w":this.l.update();2<this.p.W()&&(this.state="up",this.height=26,this.y-=19,this.k.reset());break;case "up":this.k.update();0<this.k.frame&&16>this.k.frame&&this.Y(b,80)&&(this.state="a",this.p.reset());15<this.k.frame&&(this.state="w",this.y+=19,this.height=6,this.p.reset());
break;case "a":1===this.p.W()&&(p(this.d?this.x-5:this.x+this.width-5,this.y+this.height,3,this.d,!0,!0,!1),this.state="up",this.p.reset())}},xa:function(){this.g||(this.now=k(),10<this.now-this.o&&(this.x=this.d?this.x-this.speed:this.x+this.speed,this.o=this.now,2!==this.type||"pb"!==this.state||null===this.j||this.j.g||this.j.push(this.d)))},reset:function(){this.state="w";this.g=!1;switch(this.type){case 3:this.x=200;this.y=367;this.M=this.L=0;break;case 2:this.x=-50;this.y=705;break;case 0:this.y=
251}},c:function(a){switch(this.type){case 0:this.Za(a);break;case 1:this.Ya(a);break;case 2:this.$a(a);break;case 3:this.Xa(a)}},Xa:function(a){this.l.c(a,this.x,this.y,!this.d)},Za:function(a){switch(this.state){case "d":case "w":this.l.c(a,this.x,this.y,!this.d);break;case "a":this.k.c(a,this.x,this.y,!this.d)}},$a:function(a){switch(this.state){case "t":case "w":case "d":this.l.c(a,this.x,this.y,!this.d);break;case "hb":case "pb":case "dj":this.k.c(a,this.x,this.y,!this.d)}},Ya:function(a){switch(this.state){case "w":this.l.c(a,
this.x,this.y,!this.d);break;case "up":this.k.c(a,this.x,this.y,!this.d);break;case "a":this.Ka.c(a,this.x,this.y,!this.d)}},Y:function(a,b){if(!this.d){if(l(a,{x:this.x,y:this.y+this.height/2,width:b,height:2}))return!0}else if(l(a,{x:this.x-b,y:this.y+this.height/2,width:b,height:2}))return!0;return!1},ga:function(){switch(this.type){case 0:p(this.d?this.x-this.width-5:this.x+this.width+5,this.y+this.height,2,this.d,!0,!0,!1);p(this.d?this.x-this.width-5:this.x+this.width+5,this.y+this.height,2,
this.d,!0,!0,!0);p(this.d?this.x-this.width-5:this.x+this.width+5,this.y+this.height,2,this.d,!1,!0,!0);break;case 3:p(this.d?this.x-this.width-10:this.x+this.width+10,this.y+this.height,1,this.d,!1,!0,!1)}}};L.prototype={update:function(a){0<this.H&&k()-this.sb>this.H&&(this.g=!0,this.Z&&(this.Z=!1,icebases[12].$=!0));this.jb&&(this.d?this.e>-this.speed&&this.e--:this.e<this.speed&&this.e++);this.kb&&(this.bb?this.i>-this.speed&&this.i--:this.i<this.speed&&this.i++);this.e*=this.B;this.i*=this.B;
this.x+=this.e;this.y+=this.i;this.I.update();if(!this.g){switch(this.type){case 1:l(a,this)&&(a.ma=!0,a.x=this.x+this.U,a.y=this.y-15+this.V,a.q=!0);this.U+=this.ja;this.V+=this.ka;if(-8>this.U||8<this.U)this.ja*=-1;if(-20>this.V||5<this.V)this.ka*=-1}4!==this.type&&(-5>this.x||1028<this.x||-5>this.y||800<this.y)&&(this.g=!0)}},c:function(a){this.I.c(a,this.x,this.y,this.d)},push:function(a){this.x=a?this.x-this.speed:this.x+this.speed}};I.prototype={update:function(a,b,c,e){switch(this.state){case "w":this.ma&&
(this.f.n(this.f.m.ya)||this.f.n(this.f.m.za))&&(this.f.n(this.f.m.Ba)||this.f.n(this.f.m.Aa)||this.f.n(this.f.m.Ca))?this.ma=!1:(this.f.n(this.f.m.ya)&&(this.e>-this.speed&&this.e--,this.d=!0),this.f.n(this.f.m.za)&&(this.e<this.speed&&this.e++,this.d=!1),(this.f.n(this.f.m.Ba)||this.f.n(this.f.m.Aa)||this.f.n(this.f.m.Ca))&&!this.q&&this.C&&(this.q=!0,this.F=this.C=!1,this.i=2*-this.speed,n.play("jump")),this.f.n(this.f.m.Oa)&&!this.q&&this.C&&(this.q=this.C=!1,this.F=!0,this.i=2*this.speed),this.f.n(this.f.m.Ra)&&
v.N()&&(this.G.J++,2<this.G.J&&(this.G.J=0),v.reset()),this.f.n(this.f.m.Na)&&v.N()&&(this.ga=!0,p(this.d?this.x-6:this.x+this.width-6,this.y+45,5+this.G.J,this.d,!1,!0,!1),v.reset()));this.f.n(this.f.m.Pa)&&x.N()&&(n.aa=!n.aa,x.reset());this.e*=this.B;this.i+=this.fb;this.C=!1;for(c=0;c<b.length;c++){var d=N(this,b[c]);"l"===d||"r"===d?(this.e=0,this.q=!1):"b"===d?(this.C=!0,this.F=this.q=!1):"t"===d&&(this.i*=-1)}for(c=0;c<e.length;c++)e[c].g||4!==e[c].type||(d=N(this,e[c]),"l"===d||"r"===d?(this.e=
0,this.q=!1):"b"===d?(this.C=!0,this.F=this.q=!1):"t"===d&&(this.i*=-1));this.C&&(this.i=0);this.x+=this.e;this.y+=this.i;this.x<-(this.width-2)?this.x=a.width-3:this.x>a.width-2&&(this.x=-1*(this.width-3));(.1<this.e||-.1>this.e)&&!this.q&&this.Q.update();break;case "d":this.y+=3,1E3<this.y&&(w.reset(),m.state="DIE")}},c:function(a){switch(this.state){case "w":this.q||this.F?this.ub.c(a,this.x,this.y,!this.d):this.Q.c(a,this.x,this.y,!this.d);break;case "d":this.tb.c(a,this.x,this.y,!this.d)}}};
G.prototype={update:function(a,b,c,e){switch(this.state){case "TITLE":this.f.fa()&&(this.state="STORY",q=!1);break;case "STORY":this.f.fa()&&(this.state="GAME",q=!1);break;case "END":case "DIE":this.f.fa(!0)&&(this.state="TITLE",q=!1);break;case "GAME":if(!q){for(var d=0,d=0;d<this.s.length;d++)this.s[d].update(a,b,this.Db,this.r);for(d=0;d<this.h.length;d++)this.h[d].g||(this.h[d].update(e,this.t,this.r,this.pa),l(this.t,this.h[d])&&(this.t.state="d"));for(d=0;d<this.A.length;d++)this.A[d].update(a,
c,this.t);0<y&&(a=k(),500<a-this.Ga&&(n.play("pewpew"),this.Ga=a));for(d=0;d<this.r.length;d++)this.r[d].g||this.r[d].update(this.t,this.pa);this.ea.update()}this.f.n(this.f.m.Qa)&&v.N()&&(q=!q,v.reset())}},c:function(a,b){a.clearRect(0,0,b.width,b.height);switch(this.state){case "LOADING":this.pb(a,b);break;case "TITLE":this.sa(a);this.rb(a,b);this.ea.update();break;case "STORY":this.sa(a);this.qb(a,b);this.ea.update();break;case "END":this.Ia(a,b,"You Did it! Congratulations!");break;case "DIE":this.Ia(a,
b,"Game Over!");break;case "GAME":this.sa(a);this.ra(a);for(var c=0,c=0;c<this.s.length;c++)this.s[c].c(a);for(c=0;c<this.h.length;c++)this.h[c].g||this.h[c].c(a);for(c=0;c<this.A.length;c++)this.A[c].g||this.A[c].c(a);for(c=0;c<this.r.length;c++)this.r[c].g||this.r[c].c(a);this.ob(a,this.t);q&&(a.fillStyle="#000",a.font="30pt monospace",a.textAlign="center",a.fillText("PAUSED",b.width/2,b.height/2));c=1E3/((E=new Date)-F);E!==F&&(A+=(c-A)/50,F=E)}},Ia:function(a,b,c){a.fillStyle="#000";a.fillRect(0,
0,b.width,b.height);a.fillStyle="#fff";a.font="30pt monospace";a.textAlign="center";a.fillText(c,b.width/2,b.height/2);this.ha(a,512,600,!0);z=m.J=y=0;m.A=[];m.r=[];m.t.x=512;m.t.y=700;m.t.state="w";for(a=0;a<m.h.length;a++)m.h[a].reset()},sa:function(a){for(var b=0,b=0;1024>b;b+=94)this.Da.c(a,b,482),this.Da.c(a,b+48,482,!0);for(var c=0,b=0;1024>b;b+=24)this.Sa.c(a,b,510),0===b%96&&(this.Ta.c(a,b,510),c=0),600===b&&(this.Ua.c(a,b,510),c=0),c++;a.fillStyle="#11b76d";a.fillRect(0,570,1024,80);a.fillStyle=
"#148875";a.fillRect(0,650,1024,40);a.fillStyle="#155c6f";a.fillRect(0,690,1024,100);for(b=0;1024>b;b+=15)this.cb.c(a,b,645);for(b=0;1024>b;b+=15)this.eb.c(a,b,685);for(b=0;768>b;b+=8)this.va.c(a,150,b),this.va.c(a,450,b),this.va.c(a,750,b);for(b=0;3>b;b++)this.wb.c(a,138+300*b,713),this.xb.c(a,268+300*b,713);for(b=0;1024>b;b+=48)this.hb.c(a,b,0)},ra:function(a){for(var b=0,b=0;1024>b;b+=8)this.D.c(a,b,729),this.nb.c(a,b,745);for(b=0;500>b;b+=8)this.D.c(a,b,580);for(b=600;1024>b;b+=8)this.D.c(a,b,
580);for(b=0;1024>b;b+=8)this.D.c(a,b,430);for(b=0;340>b;b+=8)this.D.c(a,b,279);for(b=400;620>b;b+=8)this.D.c(a,b,279);for(b=680;1024>b;b+=8)this.D.c(a,b,279);for(b=0;1024>b;b+=8)this.D.c(a,b,129);this.K(a,0,280,!1);this.K(a,0,430,!1);this.K(a,0,580,!1);this.K(a,924,280,!0);this.K(a,924,430,!0);this.K(a,924,580,!0);for(b=0;1024>b;b+=28)this.ea.c(a,b,740),this.Cb.c(a,b,756)},K:function(a,b,c,e){e?(this.R.c(a,b,c+100,e),this.R.c(a,b+32,c+50,e),this.R.c(a,b+64,c,e)):(this.R.c(a,b,c+100,e),this.R.c(a,
b-32,c+50,e),this.R.c(a,b-64,c,e))},ob:function(a){n.aa&&this.lb.c(a,1E3,50);a.fillStyle="red";a.fillRect(18,168,20,-4*z);this.gb.c(a,20,20);this.na.u(1);for(var b=0;11>b;b++)this.na.c(a,14,40+12*b),9==b&&this.na.u(0);this.ab.c(a,50,45+25*this.J);for(b=0;3>b;b++)this.Fa.u(b),this.Fa.c(a,55,50+25*b)},pb:function(a,b){a.fillStyle="#000";a.fillRect(0,0,b.width,b.height);a.fillStyle="white";a.font="20pt monospace";a.textAlign="center";a.fillText("Loading...",b.width/2,b.height/2)},qb:function(a,b){this.ra(a);
a.fillStyle="rgba(0, 0, 0, 0.80)";a.fillRect(0,0,b.width,b.height);var c=b.width/2;a.fillStyle="white";a.font="12pt monospace";for(var e="Oh no!;Felicity's boyfriend is losing his love!;Brave the four elements and collect the hearts before they break.;Fill the heartmeter to complete the level.;Watch out for windducks, firesprites, sandmonsters and snowmen.;Use the correct element to defeat them.;;Controls:;Arrow keys: Move left/right, Jump, Go down stairs;Z: Jump;X: Switch Element;C: Use Element;;M: Mute sounds;P: Pause".split(";"),
d=0;d<e.length;d++)a.fillText(e[d],c,100+40*d);this.ha(a,c,720)},ha:function(a,b,c,e){switch(this.vb.W()){case 0:a.fillStyle="white",a.font="15pt impact",e?a.fillText("Press any key to try again",b,c):a.fillText("Press any key to begin",b,c)}},rb:function(a,b){this.ra(a);a.fillStyle="rgba(255, 255, 255, 0.10)";a.fillRect(0,0,b.width,b.height);a.fillStyle="yellow";a.font="60pt impact";a.textAlign="center";for(var c=["Felicity","and","the Fifth Element:","Love"],e=0;e<c.length;e++)a.fillText(c[e],512,
200+100*e);this.ha(a,512,630)},ib:function(){var a=this,b=new Image;b.onload=function(){a.state="TITLE"};b.src="spritesheet.png";D[0]=b}};window.addEventListener("load",function(){m=new G});window.onblur=function(){B=!0};window.onfocus=function(){B=!1}})();
