var world=new Zdog.Illustration({element:".game",resize:"fullscreen",dragRotate:!1,rotate:{x:Zdog.TAU/8,y:0,z:Zdog.TAU/8},zoom:Math.floor(window.innerWidth/1920*12.5)/10}),debugMode=!1,Gameover=!0,Score=0;function gameover(){prompt("Your score is "+Score.toString());Gameover=!0;location.reload()}
var pieces=[],angle=0,Ice=function(b,c,a){angle+=1;this.mainGroup=new Zdog.Group({addTo:world,updateSort:!0,translate:{x:b,y:c}});this.ice1=new Zdog.Polygon({addTo:this.mainGroup,radius:a,sides:5,fill:!0,color:"#EAFEFE",rotate:{z:Zdog.TAU/24*angle}});this.ice2=this.ice1.copy({stroke:a/6,color:"#6AFEFE",translate:{z:-a/12}});this.ice3=this.ice2.copy({color:"#015DAB",translate:{z:-a/6}});this.translatedCoords={x:b*Math.cos(Zdog.TAU/8)-c*Math.sin(Zdog.TAU/8),y:b*Math.sin(Zdog.TAU/8)+c*Math.cos(Zdog.TAU/
8)};pieces.push(this)},planeGroup=new Zdog.Group({addTo:world,updateSort:!0,visible:!1}),plane1=new Zdog.Rect({addTo:planeGroup,width:100,height:2*window.innerWidth,fill:!0,color:"#015DAB",translate:{z:-25}}),plane2=new Zdog.Rect({addTo:planeGroup,width:2*window.innerWidth,height:100,fill:!0,color:"#015DAB",translate:{z:-25}}),ice1=new Ice(-180,180,100),ice2=new Ice(-350,180,50),ice3=new Ice(-320,570,100),ice4=new Ice(-130,690,50),ice5=new Ice(-720,200,100),ice6=new Ice(-480,440,50),ice7=new Ice(-305,
290,50),ice8=new Ice(200,470,100),ice9=new Ice(410,180,100),ice10=new Ice(130,310,50),ice11=new Ice(310,-570,100),ice12=new Ice(780,-180,100),ice13=new Ice(460,-120,50),ice14=new Ice(510,-500,50),ice15=new Ice(170,-160,100),ice16=new Ice(-280,-270,100),ice17=new Ice(-160,-150,50),ice18=new Ice(-530,-160,100),ice190=new Ice(-140,-460,50),IceShelf=function(b,c){this.mainGroup=new Zdog.Group({addTo:world,updateSort:!0,translate:{x:b,y:c}});this.iceShelf1=new Zdog.RoundedRect({addTo:this.mainGroup,width:120,
height:120,cornerRadius:25,fill:!0,color:"#EAFEFE",translate:{z:10}});this.iceShelf2=this.iceShelf1.copy({stroke:20,color:"#6AFEFE",translate:{z:0}});this.iceShelf3=this.iceShelf2.copy({color:"#015DAB",translate:{z:-10}});this.body=!0===debugMode?new Zdog.Rect({addTo:this.mainGroup,width:140,height:140,fill:!0,color:"#00FF00"}):{width:140,height:140};this.collisionRect={x:this.mainGroup.translate.x,y:this.mainGroup.translate.y,width:this.body.width,height:this.body.height};this.translatedCoords={x:b*
Math.cos(Zdog.TAU/8)-c*Math.sin(Zdog.TAU/8),y:b*Math.sin(Zdog.TAU/8)+c*Math.cos(Zdog.TAU/8)};this.tweener=1;this.tweenMode=!1;this.alive=!0;this.updateIce=function(){!0===this.alive&&!0===this.tweenMode&&(this.tweener-=.05*delta,this.mainGroup.scale.x=this.tweener,this.mainGroup.scale.y=this.tweener,0>=this.tweener&&(this.tweener=1,this.alive=this.tweenMode=!1,this.mainGroup.scale.x=0,this.mainGroup.scale.y=0,this.mainGroup.visible=!1,gameover()))};pieces.push(this)},iceShelf=new IceShelf(0,0),whaleTotal=
0,whaleDead=0,whales=[],whaleID=0,Whale=function(b,c){this.ID=whaleID;whaleID+=1;this.distance={x:0,y:0};this.alive=!0;1===c&&(this.distance.x=0,this.distance.y=b);2===c&&(this.distance.x=b,this.distance.y=0);3===c&&(this.distance.x=0,this.distance.y=-b);4===c&&(this.distance.x=-b,this.distance.y=0);this.velocity={x:-this.distance.x/b,y:-this.distance.y/b};this.kill=function(){this.alive=!1;this.mainGroup.visible=!1;whaleDead+=1;Score+=1};this.revive=function(a,b){1===b&&(this.distance.x=0,this.distance.y=
a);2===b&&(this.distance.x=a,this.distance.y=0);3===b&&(this.distance.x=0,this.distance.y=-a);4===b&&(this.distance.x=-a,this.distance.y=0);this.velocity={x:-this.distance.x/a,y:-this.distance.y/a};1===b&&(this.body.translate={x:0,y:85},this.body.width=170,this.body.height=220,this.holder.y=85);2===b&&(this.body.translate={x:85,y:0},this.body.width=220,this.body.height=170,this.holder.x=85);3===b&&(this.body.translate={x:0,y:-85},this.body.width=170,this.body.height=220,this.holder.y=-85);4===b&&
(this.body.translate={x:-85,y:0},this.body.width=220,this.body.height=170,this.holder.x=-85);this.alive=!0;this.mainGroup.visible=!0;this.tweener=1;this.tweenMode=!1;this.mainGroup.scale.x=1;this.mainGroup.scale.y=1;this.mainGroup.translate={x:this.distance.x,y:this.distance.y};this.mainGroup.rotate={z:-(b-1)*Zdog.TAU/4}};this.mainGroup=new Zdog.Group({addTo:world,updateSort:!0,translate:{x:this.distance.x,y:this.distance.y},rotate:{z:-(c-1)*Zdog.TAU/4}});this.whaleHead1=new Zdog.Shape({addTo:this.mainGroup,
path:[{x:0,y:-10},{x:40,y:40},{x:-40,y:40}],stroke:25,fill:!0,color:"#FFFFFF"});this.whaleHead2=this.whaleHead1.copy({color:"#000000",translate:{z:6.25}});this.whaleHead3=this.whaleHead1.copy({color:"#000000",translate:{z:12.5}});this.whaleHead4=this.whaleHead1.copy({color:"#000000",translate:{z:18.75}});this.whaleHead5=this.whaleHead1.copy({color:"#000000",translate:{z:25}});this.whaleHead6=this.whaleHead1.copy({color:"#000000",translate:{z:31.25}});this.whaleHeadShadow=this.whaleHead1.copy({color:"#015DAB",
translate:{z:-25}});this.whaleBody1=new Zdog.Shape({addTo:this.mainGroup,path:[{x:0,y:150},{x:40,y:40},{x:-40,y:40}],stroke:25,fill:!0,color:"#FFFFFF"});this.whaleBody2=this.whaleBody1.copy({color:"#000000",translate:{z:6.25}});this.whaleBody3=this.whaleBody1.copy({color:"#000000",translate:{z:12.5}});this.whaleBody4=this.whaleBody1.copy({color:"#000000",translate:{z:18.75}});this.whaleBody5=this.whaleBody1.copy({color:"#000000",translate:{z:25}});this.whaleBody6=this.whaleBody1.copy({color:"#000000",
translate:{z:31.25}});this.whaleBodyhadow=this.whaleBody1.copy({color:"#015DAB",translate:{z:-25}});this.whaleTail1=new Zdog.Ellipse({addTo:this.mainGroup,width:30,height:15,fill:!0,stroke:15,color:"#000000",translate:{x:-15,y:175,z:18.75},rotate:{z:-Zdog.TAU/8}});this.whaleTail2=this.whaleTail1.copy({translate:{x:15,y:175,z:18.75},rotate:{z:Zdog.TAU/8}});this.whaleDorsal1=new Zdog.Shape({addTo:this.mainGroup,path:[{x:0,y:-20},{x:20,y:20},{x:-20,y:20}],stroke:10,fill:!0,color:"#222222",translate:{y:65,
z:72},rotate:{x:-Zdog.TAU/4,y:Zdog.TAU/4}});this.whaleFin1=new Zdog.Ellipse({addTo:this.mainGroup,width:80,height:25,fill:!0,stroke:10,color:"#000000",translate:{x:-50,y:60,z:18.75},rotate:{z:-Zdog.TAU/8}});this.whaleFin2=this.whaleFin1.copy({translate:{x:50,y:60,z:18.75},rotate:{z:Zdog.TAU/8}});this.whaleEye1=new Zdog.Shape({addTo:this.mainGroup,path:[{x:0,y:-20,z:0},{x:10,y:10,z:25},{x:-10,y:10,z:25}],stroke:3,fill:!0,color:"#FFFFFF",translate:{x:20,y:15,z:25},rotate:{y:-Zdog.TAU/4}});this.whaleEye2=
this.whaleEye1.copy({translate:{x:-20,y:15,z:25},rotate:{y:Zdog.TAU/4}});this.rgb=function(a,b,c){return"rgb("+a+","+b+","+c+")"};this.setMainColor=function(a){this.whaleHead2.color=this.rgb(a,a,a);this.whaleHead3.color=this.rgb(a,a,a);this.whaleHead4.color=this.rgb(a,a,a);this.whaleHead5.color=this.rgb(a,a,a);this.whaleHead6.color=this.rgb(a,a,a);this.whaleBody2.color=this.rgb(a,a,a);this.whaleBody3.color=this.rgb(a,a,a);this.whaleBody4.color=this.rgb(a,a,a);this.whaleBody5.color=this.rgb(a,a,a);
this.whaleBody6.color=this.rgb(a,a,a);this.whaleTail1.color=this.rgb(a,a,a);this.whaleTail2.color=this.rgb(a,a,a);this.whaleDorsal1.color=this.rgb(a+34,a+34,a+34);this.whaleFin1.color=this.rgb(a,a,a);this.whaleFin2.color=this.rgb(a,a,a)};this.setSecondaryColor=function(a){this.whaleHead1.color=this.rgb(a,a,a);this.whaleBody1.color=this.rgb(a,a,a);this.whaleEye1.color=this.rgb(a,a,a);this.whaleEye2.color=this.rgb(a,a,a)};this.fullColor=function(){this.colorOut=Math.min(221,7*this.ID);this.setMainColor(this.colorOut);
this.setSecondaryColor(255-this.colorOut)};this.fullColor();this.holder={x:0,y:0};!0===debugMode?(1===c&&(this.body=new Zdog.Rect({addTo:world,width:170,height:220,fill:!0,color:"#00FF00",translate:{y:85}}),this.holder.y=85),2===c&&(this.body=new Zdog.Rect({addTo:world,width:220,height:170,fill:!0,color:"#00FF00",translate:{x:85}}),this.holder.x=85),3===c&&(this.body=new Zdog.Rect({addTo:world,width:170,height:220,fill:!0,color:"#00FF00",translate:{y:-85}}),this.holder.y=-85),4===c&&(this.body=new Zdog.Rect({addTo:world,
width:220,height:170,fill:!0,color:"#00FF00",translate:{x:-85}}),this.holder.x=-85)):(1===c&&(this.body={translate:{x:0,y:85},width:170,height:220},this.holder.y=85),2===c&&(this.body={translate:{x:85,y:0},width:220,height:170},this.holder.x=85),3===c&&(this.body={translate:{x:0,y:-85},width:170,height:220},this.holder.y=-85),4===c&&(this.body={translate:{x:-85,y:0},width:220,height:170},this.holder.x=-85));this.collisionRect={x:this.mainGroup.translate.x+this.body.translate.x,y:this.mainGroup.translate.y+
this.body.translate.y,width:this.body.width,height:this.body.height};this.translatedCoords={x:this.mainGroup.translate.x*Math.cos(Zdog.TAU/8)-this.mainGroup.translate.y*Math.sin(Zdog.TAU/8),y:this.mainGroup.translate.x*Math.sin(Zdog.TAU/8)+this.mainGroup.translate.y*Math.cos(Zdog.TAU/8)};this.tweener=1;this.tweenMode=!1;this.updateWhale=function(a,c){!0===this.alive&&(this.mainGroup.translate.x+=this.velocity.x*a*speed,this.mainGroup.translate.y+=this.velocity.y*a*speed,this.out=Math.sin((this.translatedCoords.x+
this.translatedCoords.y)/b+c),this.mainGroup.translate.z=15*this.out,this.mainGroup.rotate.y=this.out*angle,this.collisionRect={x:this.mainGroup.translate.x+this.holder.x,y:this.mainGroup.translate.y+this.holder.y,width:this.body.width,height:this.body.height},this.body.translate.x=this.mainGroup.translate.x+this.holder.x,this.body.translate.y=this.mainGroup.translate.y+this.holder.y);!0===this.tweenMode&&(this.tweener-=.05*a,this.mainGroup.scale.x=this.tweener,this.mainGroup.scale.y=this.tweener,
0>=this.tweener&&(this.tweener=1,this.tweenMode=!1,this.mainGroup.scale.x=1,this.mainGroup.scale.y=1,this.kill()))};whales.push(this)};function randomSpawn(){for(var b=[],c=0,a=0;4>b.length;a++){for(var d=Math.floor(4*Math.random()+1),e=0;e<b.length;e++)d===b[e]&&(c+=1);0===c&&b.push(d);c=0}return b}randomPos=randomSpawn();function createWhale(b,c,a){b=new Whale(b,c);!0===a&&b.kill()}function addWhale(b){for(var c=1;c<=b;c++)createWhale(800,randomPos[(c-1)%randomPos.length],!0),whaleTotal+=1}
function initWhale(b){for(var c=1;c<=b;c++)window.setTimeout(createWhale,1E3*c,800,randomPos[(c-1)%randomPos.length]),whaleTotal+=1}function Play(){Gameover=!1;initWhale(4)}var Playhit=!1;window.addEventListener("pointerdown",function(){!1===Playhit&&(Play(),Playhit=!0)});function spawnOldWhale(b,c,a){whales[b].revive(c,a)}function recycleWhale(){randomPos=randomSpawn();for(var b=0;b<whales.length;b++)window.setTimeout(spawnOldWhale,1E3*(b+1),b,800,randomPos[b%randomPos.length])}
function detectCollision(b,c){if(b.x-b.width/2<c.x+c.width/2&&b.x+b.width/2>c.x-c.width/2&&b.y-b.height/2<c.y+c.height/2&&b.y+b.height/2>c.y-c.height/2)return!0}
var playerGroup=new Zdog.Group({addTo:iceShelf.mainGroup,updateSort:!0,translate:{z:85},rotate:{z:Zdog.TAU/4}}),playerBodyGroup=new Zdog.Group({addTo:playerGroup,updateSort:!0}),player1=new Zdog.RoundedRect({addTo:playerBodyGroup,width:80,height:50,cornerRadius:25,stroke:25,fill:!0,color:"#7730E0",rotate:{y:Zdog.TAU/4}}),player2=player1.copy({translate:{x:6.25}}),player3=player1.copy({translate:{x:12.5}}),playerFoot1=new Zdog.Cylinder({addTo:playerGroup,diameter:4,length:20,stroke:5,fill:!0,color:"#F87418",
translate:{x:6.25,y:15,z:-60}}),playerFoot2=playerFoot1.copy({translate:{x:6.25,y:-15,z:-60}}),playerFootSole1=new Zdog.Polygon({addTo:playerGroup,radius:10,sides:5,stroke:5,fill:!0,color:"#F87418",translate:{x:8.75,y:15,z:-70},rotate:{z:-Zdog.TAU/6}}),playerFootSole2=playerFootSole1.copy({translate:{x:8.75,y:-15,z:-70}}),playerArm1=new Zdog.Ellipse({addTo:playerGroup,width:20,height:50,stroke:10,fill:!0,color:"#5924A8",translate:{x:6.25,y:40,z:-10},rotate:{x:Zdog.TAU/3.42,z:Zdog.TAU/24}}),playerArm2=
playerArm1.copy({translate:{x:6.25,y:-40,z:-10},rotate:{x:-Zdog.TAU/3.42,z:Zdog.TAU/24}}),playerFrontGroup=new Zdog.Group({addTo:playerGroup,updateSort:!1}),playerFeathers=new Zdog.RoundedRect({addTo:playerFrontGroup,width:60,height:50,cornerRadius:25,fill:!0,color:"#FFFFFF",translate:{x:25,z:-10},rotate:{y:Zdog.TAU/4}}),playerTop1=new Zdog.Ellipse({addTo:playerFrontGroup,diameter:30,fill:!0,color:"#FFFFFF",translate:{x:25,y:-10,z:20},rotate:{y:Zdog.TAU/4}}),playerTop2=playerTop1.copy({translate:{x:25,
y:10,z:20}}),playerRightEye1=new Zdog.Ellipse({addTo:playerFrontGroup,diameter:17,fill:!0,color:"#000000",translate:{x:25,y:-10,z:20},rotate:{y:Zdog.TAU/4}}),playerLeftEye1=playerRightEye1.copy({translate:{x:25,y:10,z:20}}),playerRightEye2=new Zdog.Ellipse({addTo:playerFrontGroup,diameter:7,fill:!0,color:"#FFFFFF",translate:{x:25,y:-12,z:23},rotate:{y:Zdog.TAU/4}}),playerLeftEye2=playerRightEye2.copy({translate:{x:25,y:8,z:23}}),playerRightEye3=new Zdog.Ellipse({addTo:playerFrontGroup,diameter:3,
fill:!0,color:"#FFFFFF",translate:{x:25,y:-8,z:15},rotate:{y:Zdog.TAU/4}}),playerLeftEye3=playerRightEye3.copy({translate:{x:25,y:12,z:15}}),playerRightCheek=new Zdog.Ellipse({addTo:playerFrontGroup,width:7,height:10,fill:!0,color:"#FFD1D3",translate:{x:25,y:-13,z:7},rotate:{y:Zdog.TAU/4},visible:!0}),playerLeftCheek=playerRightCheek.copy({translate:{x:25,y:13,z:7}}),playerPeak=new Zdog.Cone({addTo:playerFrontGroup,diameter:10,length:12,stroke:5,fill:!0,color:"#FFA50D",translate:{x:25,y:0,z:3},rotate:{y:-Zdog.TAU/
4}}),IceBerg=function(b,c){this.iceBergGroup=new Zdog.Group({addTo:world,updateSort:!0,translate:{x:b,y:c},rotate:{z:Zdog.TAU/4.48}});this.spike1=new Zdog.Cone({addTo:this.iceBergGroup,diameter:75,length:150,stroke:5,fill:!0,color:"#EAFEFE",translate:{x:18.3,y:18.3}});this.spike2=this.spike1.copy({addTo:this.iceBergGroup,length:100,translate:{x:-25,y:-25}});this.spike3=this.spike1.copy({addTo:this.iceBergGroup,length:125,translate:{x:25,y:-25}});this.spikeBase1=new Zdog.Ellipse({addTo:this.iceBergGroup,
diameter:75,stroke:15,fill:!0,color:"#6AFEFE",translate:{x:18.3,y:18.3,z:-7.5}});this.spikeBase2=this.spikeBase1.copy({addTo:this.iceBergGroup,translate:{x:-25,y:-25,z:-7.5}});this.spikebase3=this.spikeBase1.copy({addTo:this.iceBergGroup,translate:{x:25,y:-25,z:-7.5}});this.spikeSunk1=new Zdog.Cone({addTo:this.iceBergGroup,diameter:75,length:200,stroke:5,fill:!0,color:"#015DAB",translate:{x:18.3,y:18.3,z:-15},rotate:{y:Zdog.TAU/2}});this.spikeSunk2=this.spikeSunk1.copy({addTo:this.iceBergGroup,length:150,
translate:{x:-25,y:-25,z:-15}});this.spikeSunk3=this.spikeSunk1.copy({addTo:this.iceBergGroup,length:175,translate:{x:25,y:-25,z:-15}})},berg1=new IceBerg(-500,225),berg2=new IceBerg(-175,450),berg3=new IceBerg(225,225),Buoy=function(b,c,a,d,e){this.mainGroup=new Zdog.Group({addTo:world,translate:{x:b,y:c},updateSort:!0});this.buoySunk=new Zdog.Hemisphere({addTo:this.mainGroup,diameter:75,fill:!0,color:"#015DAB",rotate:{y:Zdog.TAU/2}});this.buoyBody=new Zdog.Cylinder({addTo:this.mainGroup,diameter:75,
length:25,fill:!0,color:a,frontFace:d,translate:{z:12.5}});this.buoyHeight=new Zdog.Box({addTo:this.mainGroup,width:20,height:20,depth:50,stroke:5,fill:!1,color:a,translate:{z:50}});this.buoyAntenna1=new Zdog.Box({addTo:this.mainGroup,width:30,height:30,depth:50,fill:!0,color:d,leftFace:e,rightFace:a,topFace:a,bottomFace:e,translate:{z:95}});this.buoyAntenna2=new Zdog.Ellipse({addTo:this.mainGroup,diameter:60,stroke:5,fill:!1,color:d,translate:{z:121}});this.buoyAntenna3=new Zdog.Shape({addTo:this.mainGroup,
path:[{x:-30,y:0},{x:30,y:0},{move:{x:0,y:-30}},{x:0,y:30}],closed:!1,stroke:5,color:d,translate:{z:121}});this.translatedCoords={x:b*Math.cos(Zdog.TAU/8)-c*Math.sin(Zdog.TAU/8),y:b*Math.sin(Zdog.TAU/8)+c*Math.cos(Zdog.TAU/8)};pieces.push(this)},buoy1=new Buoy(-300,-120,"#CA000E","#D5333E","#98000B"),buoy2=new Buoy(-120,-300,"#0BD731","#2BE24E","#08A525"),buoy3=new Buoy(300,-120,"#E1240B","#EC432D","#AF1C09"),lightHouseGroup=new Zdog.Group({addTo:world,translate:{x:300,y:-335},updateSort:!0}),lightHouseiceShelf1=
new Zdog.Ellipse({addTo:lightHouseGroup,width:200,height:200,cornerRadius:25,fill:!0,color:"#8D9AA3",translate:{z:10}}),lightHouseiceShelf2=lightHouseiceShelf1.copy({stroke:20,color:"#849199",translate:{z:0}}),lightHouseiceShelf3=lightHouseiceShelf2.copy({color:"#015DAB",translate:{z:-10}}),lightHouseBase=new Zdog.Cylinder({addTo:lightHouseGroup,diameter:125,length:25,color:"#7E909C",frontFace:"#98A6B0",translate:{z:25}}),lightHouse1=new Zdog.Cylinder({addTo:lightHouseGroup,diameter:100,length:50,
color:"#C512E8",translate:{z:62.5}}),lightHouse2=lightHouse1.copy({color:"#FFF8E5",translate:{z:112.5}}),lightHouse3=lightHouse1.copy({color:"#C512E8",translate:{z:162.5}}),lightHouse4=lightHouse1.copy({color:"#FFF8E5",translate:{z:212.5}}),lightHouse5=lightHouse1.copy({color:"#C512E8",translate:{z:262.5}}),lightHouse6=lightHouse1.copy({color:"#FFF8E5",translate:{z:312.5}}),lightHouse7=new Zdog.Cone({addTo:lightHouseGroup,diameter:100,length:100,stroke:10,fill:!0,color:"#C512E8",translate:{z:337.5}}),
lightCone=new Zdog.Group({addTo:lightHouseGroup,updateSort:!0,translate:{z:437.5}}),lightSphere=new Zdog.Shape({addTo:lightCone,stroke:25,color:"#FFFF99"}),lightCone1=new Zdog.Cone({addTo:lightCone,diameter:125,length:250,fill:!0,color:"#FFFF99",backface:"#FFFF00",translate:{y:250},rotate:{x:Zdog.TAU/4}}),lightCone2=lightCone1.copy({translate:{y:-250},rotate:{x:-Zdog.TAU/4}}),Boat=function(b,c){this.mainGroup=new Zdog.Group({addTo:world,updateSort:!0,translate:{x:b,y:c}});this.boatBase=new Zdog.RoundedRect({addTo:this.mainGroup,
width:125,height:200,cornerRadius:25,fill:!0,color:"#BF370E",translate:{z:-12.5}});this.boatBody1=new Zdog.RoundedRect({addTo:this.mainGroup,width:125,height:200,cornerRadius:25,stroke:25,color:"#FF4912"});this.boatBody2=this.boatBody1.copy({color:"#FF4912",translate:{z:12.5}});this.boatBody3=this.boatBody1.copy({color:"#FF6D41",translate:{z:25}});this.boatBody4=new Zdog.Shape({addTo:this.mainGroup,path:[{x:-30,y:0},{x:30,y:0},{move:{x:-30,y:45}},{x:30,y:45},{move:{x:-30,y:-45}},{x:30,y:-45}],closed:!1,
stroke:25,color:"#FF4912"});this.boatBodySunk=this.boatBody1.copy({color:"#015DAB",translate:{z:-25}});this.engineGroup=new Zdog.Group({addTo:this.mainGroup,updateSort:!0,translate:{y:105,z:62.5}});this.engine1=new Zdog.Box({addTo:this.engineGroup,width:40,height:50,depth:40,stroke:10,fill:!0,color:"#222222",leftFace:"#111111",rightFace:"#111111",topFace:"#111111",bottomFace:"#111111"});this.engine2=new Zdog.Shape({addTo:this.engineGroup,path:[{x:0,y:-25},{x:0,y:25}],stroke:15,color:"#111111",translate:{y:-50,
z:-10}});this.engine3=new Zdog.Box({addTo:this.engineGroup,width:15,height:15,depth:50,fill:!0,color:"#111111",bottomFace:"#222222",translate:{y:20,z:-50}});this.engine4=new Zdog.Box({addTo:this.engineGroup,width:15,height:15,depth:25,fill:!0,color:"#015DAB",translate:{y:20,z:-87.5}});this.engine5=new Zdog.Box({addTo:this.engineGroup,width:15,height:25,depth:15,fill:!0,color:"#015DAB",translate:{y:25,z:-107.5}});this.engine6=new Zdog.Ellipse({addTo:this.engineGroup,diameter:45,fill:!0,color:"#015DAB",
translate:{y:40,z:-107.5},rotate:{x:Zdog.TAU/4}});this.translatedCoords={x:b*Math.cos(Zdog.TAU/8)-c*Math.sin(Zdog.TAU/8),y:b*Math.sin(Zdog.TAU/8)+c*Math.cos(Zdog.TAU/8)};pieces.push(this)},boat=new Boat(575,-300),hero=new Zdog.Rect({addTo:world,width:40,height:40,fill:!0,color:"#710071",leftFace:"#aa00aa",rightFace:"#e200e2",topFace:"#ff1cff",bottomFace:"#fe55fe",translate:{x:0,y:0,z:0},visible:!1});world.updateRenderGraph();var lastFrame=Date.now(),currentFrame=0,delta=0,counter=0;
angle=Zdog.TAU/48;delta=0;
var speed=1,level=0,Interaction=function(b,c){this.mainGroup=new Zdog.Group({addTo:world,updateSort:!0,translate:{x:b,y:c}});this.iceShelf1=new Zdog.RoundedRect({addTo:this.mainGroup,width:100,height:100,cornerRadius:25,fill:!0,color:"#EAFEFE",translate:{z:10}});this.iceShelf2=this.iceShelf1.copy({stroke:20,color:"#6AFEFE",translate:{z:0}});this.iceShelf3=this.iceShelf2.copy({color:"#015DAB",translate:{z:-10}});this.body=new Zdog.RoundedRect({addTo:this.mainGroup,width:100,height:100,cornerRadius:25,
fill:!0,color:"#FFFFFF",visible:!1});this.collisionRect={x:this.mainGroup.translate.x,y:this.mainGroup.translate.y,width:this.body.width,height:this.body.height};this.updateInteraction=function(){this.collisionRect={x:this.mainGroup.translate.x,y:this.mainGroup.translate.y,width:this.body.width,height:this.body.height}}},col=new Interaction(0,0);function rotateZ(b,c){var a={};a.x=b*Math.cos(Zdog.TAU/8)+c*Math.sin(Zdog.TAU/8);a.y=c*Math.sin(Zdog.TAU/8)-b*Math.sin(Zdog.TAU/8);return a}
function rotateX(b,c){var a={};a.x=b*Math.cos(Zdog.TAU/8);a.y=b*Math.sin(Zdog.TAU/8);return a}var clientX=0,clientY=0;window.addEventListener("pointermove",function(b){clientX=b.clientX;clientY=b.clientY});window.addEventListener("pointerdown",function(b){clientX=b.clientX;clientY=b.clientY});
function updateIceBlock(b,c){var a=b-window.innerWidth/2,d=c-window.innerHeight/2,e=rotateZ(a,d).x;a=rotateZ(a,d).y;d=col.mainGroup.translate.x;var f=col.mainGroup.translate.y,g=e-d,h=a-f;20<Math.sqrt(g*g+h*h)&&(e=Math.atan2(f-a,d-e)+Math.PI,a=10*Math.sin(e)*delta,col.mainGroup.translate.x+=10*Math.cos(e)*delta,col.mainGroup.translate.y+=a);col.updateInteraction()}
function update(){if(!1===Gameover){currentFrame=Date.now();delta=(currentFrame-lastFrame)/16;5<delta&&(delta=5);lastFrame=Date.now();counter+=.03*delta;for(var b=0;b<pieces.length;b++){var c=pieces[b],a=Math.sin(c.translatedCoords.x+c.translatedCoords.y+counter);c.mainGroup.translate.z=15*a;c.mainGroup.rotate.y=a*angle}for(b=0;b<whales.length;b++)c=whales[b],!0===c.alive&&(c.updateWhale(delta,counter),detectCollision(c.collisionRect,iceShelf.collisionRect)&&(iceShelf.tweenMode=!0),detectCollision(c.collisionRect,
col.collisionRect)&&(c.tweenMode=!0));iceShelf.updateIce();whaleDead===whaleTotal&&(level+=1,speed+=.25,0===level%2&&0!==level&&64>=level&&addWhale(1),recycleWhale(),whaleDead=0);counter>=2*Math.PI&&(counter=0);lightCone.rotate.z+=.01*delta;lightCone.rotate.z>=Zdog.TAU&&(lightCone.rotate.z=0);updateIceBlock(clientX,clientY)}world.updateRenderGraph();requestAnimationFrame(update)}update();
document.addEventListener("keydown",function(b){87===b.keyCode&&(hero.translate.y-=10);65===b.keyCode&&(hero.translate.x-=10);68===b.keyCode&&(hero.translate.x+=10);83===b.keyCode&&(hero.translate.y+=10)});window.addEventListener("resize",function(){world.zoom=Math.floor(window.innerWidth/1920*12.5)/10});
